### ISSUE TITLE
官方Demo运行起来,打开APP就崩溃

### ISSUE THREAD

**Issue by clbDream** [didi/DoraemonKit#1018]
Android系统  模拟器7.1.2  真机小米12都是

2022-04-26 20:36:03.232 1279-1279/? E/vendor.qti.hardware.perf-hal-service: Unknown params
2022-04-26 20:36:03.233 1279-1321/? E/ANDR-PERF-OPTSHANDLER: HWC, SF, RE TIDs <= 0, set_pid_affine failed
2022-04-26 20:36:03.233 1279-1321/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [11, 8]
2022-04-26 20:36:03.246 1173-1273/? E/minksocket: MinkIPC_QRTR_Service: client with node 1 port 5cfa went down
2022-04-26 20:36:03.247 1173-1273/? E/minksocket: MinkIPC_QRTR_Service: client with node 1 port 5cfb went down
2022-04-26 20:36:03.248 1173-1273/? E/minksocket: MinkIPC_QRTR_Service: client with node 1 port 5cfc went down
2022-04-26 20:36:03.251 1173-1273/? E/minksocket: MinkIPC_QRTR_Service: client with node 1 port 5cfd went down
2022-04-26 20:36:03.253 1173-1273/? E/minksocket: MinkIPC_QRTR_Service: client with node 1 port 5cfe went down
2022-04-26 20:36:03.258 1173-1273/? E/minksocket: MinkIPC_QRTR_Service: client with node 1 port 5cff went down
2022-04-26 20:36:03.460 1279-1279/? E/vendor.qti.hardware.perf-hal-service: Unknown params
2022-04-26 20:36:03.461 1279-1321/? E/ANDR-PERF-OPTSHANDLER: HWC, SF, RE TIDs <= 0, set_pid_affine failed
2022-04-26 20:36:03.461 1279-1321/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [11, 8]
2022-04-26 20:36:03.468 1173-1273/? E/minksocket: MinkIPC_QRTR_Service: client with node 1 port 5d00 went down
2022-04-26 20:36:03.468 1173-1273/? E/minksocket: MinkIPC_QRTR_Service: client with node 1 port 5d01 went down
2022-04-26 20:36:03.469 1173-1273/? E/minksocket: MinkIPC_QRTR_Service: client with node 1 port 5d02 went down
2022-04-26 20:36:03.470 1173-1273/? E/minksocket: MinkIPC_QRTR_Service: client with node 1 port 5d03 went down
2022-04-26 20:36:03.472 1173-1273/? E/minksocket: MinkIPC_QRTR_Service: client with node 1 port 5d04 went down
2022-04-26 20:36:03.478 1173-1273/? E/minksocket: MinkIPC_QRTR_Service: client with node 1 port 5d05 went down
2022-04-26 20:36:03.529 31512-31512/? E/QuickstepAppTransitionManagerImpl: getActivityLaunchOptions   iconLoc=Rect(586, 1641 - 758, 1813)
    
    --------- beginning of system
2022-04-26 20:36:03.536 1279-1279/? E/vendor.qti.hardware.perf-hal-service: Unknown params
2022-04-26 20:36:03.536 1279-1326/? E/ANDR-PERF-LM: MetaMeter: handleAsync() 166: AdaptLaunch Invalid Async
2022-04-26 20:36:03.537 1279-1326/? E/ANDR-PERF-LM: MetaMeter: handleAsync() 166: AdaptLaunch Invalid Async
2022-04-26 20:36:03.538 2341-6737/? E/ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
2022-04-26 20:36:03.575 1279-1326/? E/ANDR-PERF-LM: MetaMeter: handleAsync() 166: AdaptLaunch Invalid Async
2022-04-26 20:36:03.575 1279-1279/? E/vendor.qti.hardware.perf-hal-service: Unknown params
2022-04-26 20:36:03.577 1279-1279/? E/vendor.qti.hardware.perf-hal-service: Unknown params
2022-04-26 20:36:03.586 31512-31630/? E/LauncherAnimationRunner: onAnimationStart
2022-04-26 20:36:03.586 31512-31630/? E/LauncherAnimationRunner: onAnimationStart:   mode=1   taskId=1996   isTranslucent=false
2022-04-26 20:36:03.586 31512-31630/? E/LauncherAnimationRunner: onAnimationStart:   mode=0   taskId=2036   isTranslucent=false
2022-04-26 20:36:03.588 31512-31512/? E/QuickstepAppTransitionManagerImpl: startIconLaunchAnimator:launcherClosing=true   iconLoc=Rect(586, 1641 - 758, 1813)
2022-04-26 20:36:03.588 31512-31512/? E/QuickstepAppTransitionManagerImpl: startOpeningWindowAnimators:iconLoc=Rect(586, 1641 - 758, 1813)
2022-04-26 20:36:03.588 31512-31512/? E/ClipAnimationHelper: updateSourceStack  mSourceInsets=Rect(0, 87 - 0, 44), mSourceStackBounds=Rect(0, 0 - 1080, 2400)
2022-04-26 20:36:03.588 31512-31512/? E/ClipAnimationHelper: updateHomeStack  mSourceInsets=Rect(0, 87 - 0, 44), mHomeStackBounds=Rect(0, 0 - 1080, 2400)
2022-04-26 20:36:03.588 31512-31512/? E/ClipAnimationHelper: updateTargetRect  mSourceRect=RectF(0.0, 87.0, 1080.0, 2487.0)   mTargetRect=RectF(0.0, 0.0, 1080.0, 2400.0)   mSourceWindowClipInsets=RectF(0.0, 87.0, 0.0, 0.0)   mHomeStackBounds=Rect(0, 0 - 1080, 2400)   targetRect=Rect(0, 0 - 1080, 2400)
2022-04-26 20:36:03.591 31512-31512/? E/QuickstepAppTransitionManagerImpl: startLauncherContentAnimator:isAppOpening=true
2022-04-26 20:36:03.596 1279-1279/? E/vendor.qti.hardware.perf-hal-service: Unknown params
2022-04-26 20:36:03.605 1279-1326/? E/ANDR-PERF-LM: MetaMeter: handleAsync() 166: AdaptLaunch Invalid Async
2022-04-26 20:36:03.660 31512-2039/? E/ActivityManagerWrapper: get all recent tasks force including 2036
2022-04-26 20:36:03.661 31512-2039/? E/ActivityManagerWrapper: getRecentTasks: size=2
2022-04-26 20:36:03.661 31512-2039/? E/ActivityManagerWrapper: getRecentTasks: taskId=2036   userId=0   baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.didichuxing.doraemondemo/.MainDebugActivityOkhttpV3 }
2022-04-26 20:36:03.661 31512-2039/? E/ActivityManagerWrapper: getRecentTasks: taskId=2027   userId=0   baseIntent=Intent { flg=0x10000000 cmp=com.talklife.yinman/.ui.me.login.LoginActivity }
2022-04-26 20:36:03.733 30802-30802/com.didichuxing.doraemondemo E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/com.didichuxing.doraemondemo/shared_prefs/authStatus_com.didichuxing.doraemondemo����������������������������������������������������������������������������������������������������������������������������������������������.xml
2022-04-26 20:36:03.733 30802-30802/com.didichuxing.doraemondemo E/PermissionCheck: permission check result is: 601
2022-04-26 20:36:03.756 31512-20015/? E/Launcher.Transfer: transfer is closed
2022-04-26 20:36:03.782 30802-30802/com.didichuxing.doraemondemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.didichuxing.doraemondemo, PID: 30802
    java.lang.ExceptionInInitializerError
        at me.weishu.epic.art.method.ArtMethod.getEntryPointFromQuickCompiledCode(ArtMethod.java:404)
        at me.weishu.epic.art.Epic.hookMethod(Epic.java:105)
        at me.weishu.epic.art.Epic.hookMethod(Epic.java:80)
        at de.robv.android.xposed.DexposedBridge.hookMethod(DexposedBridge.java:122)
        at de.robv.android.xposed.DexposedBridge.findAndHookMethod(DexposedBridge.java:176)
        at com.didichuxing.doraemonkit.kit.test.util.XposedHookUtils.hookViewOnClickListener(XposedHookUtils.kt:101)
        at com.didichuxing.doraemonkit.kit.test.util.XposedHookUtils.globalHook(XposedHookUtils.kt:95)
        at com.didichuxing.doraemonkit.kit.mc.ability.DokitMcModuleProcessor.proceed(DokitMcModuleProcessor.kt:81)
        at com.didichuxing.doraemonkit.DoKitReal.globalRunTimeHook(DoKitReal.kt:251)
        at com.didichuxing.doraemonkit.DoKitReal.install(DoKitReal.kt:94)
        at com.didichuxing.doraemonkit.DoKit$Builder.build(DoKit.kt:288)
        at com.didichuxing.doraemondemo.App.onCreate(App.kt:127)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6936)
        at android.app.ActivityThread.access$1600(ActivityThread.java:264)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2103)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8088)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
     Caused by: java.lang.RuntimeException: API LEVEL: 31 is not supported now : (
        at me.weishu.epic.art.method.Offset.initFields(Offset.java:165)
        at me.weishu.epic.art.method.Offset.<clinit>(Offset.java:53)
        at me.weishu.epic.art.method.ArtMethod.getEntryPointFromQuickCompiledCode(ArtMethod.java:404) 
        at me.weishu.epic.art.Epic.hookMethod(Epic.java:105) 
        at me.weishu.epic.art.Epic.hookMethod(Epic.java:80) 
        at de.robv.android.xposed.DexposedBridge.hookMethod(DexposedBridge.java:122) 
        at de.robv.android.xposed.DexposedBridge.findAndHookMethod(DexposedBridge.java:176) 
        at com.didichuxing.doraemonkit.kit.test.util.XposedHookUtils.hookViewOnClickListener(XposedHookUtils.kt:101) 
        at com.didichuxing.doraemonkit.kit.test.util.XposedHookUtils.globalHook(XposedHookUtils.kt:95) 
        at com.didichuxing.doraemonkit.kit.mc.ability.DokitMcModuleProcessor.proceed(DokitMcModuleProcessor.kt:81) 
        at com.didichuxing.doraemonkit.DoKitReal.globalRunTimeHook(DoKitReal.kt:251) 
        at com.didichuxing.doraemonkit.DoKitReal.install(DoKitReal.kt:94) 
        at com.didichuxing.doraemonkit.DoKit$Builder.build(DoKit.kt:288) 
        at com.didichuxing.doraemondemo.App.onCreate(App.kt:127) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6936) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:264) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2103) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:210) 
        at android.os.Looper.loop(Looper.java:299) 
        at android.app.ActivityThread.main(ActivityThread.java:8088) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045) 
2022-04-26 20:36:03.785 6967-7089/? E/OOMEventManager: oom event not support this pkg, dismiss this!
2022-04-26 20:36:03.829 1279-1321/? E/ANDR-PERF-OPTSHANDLER: Perflock resource /sys/class/devfreq/soc:qcom,cpubw/max_freq not supported
2022-04-26 20:36:03.829 1279-1321/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [6, 6]
2022-04-26 20:36:03.829 1279-1321/? E/ANDR-PERF-OPTSHANDLER: Perflock resource /sys/class/devfreq/soc:qcom,cpubw/min_freq not supported
2022-04-26 20:36:03.829 1279-1321/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [6, 0]
2022-04-26 20:36:03.830 1279-1321/? E/ANDR-PERF-OPTSHANDLER: Perflock resource /sys/class/devfreq/soc:qcom,cpu0-llcc-ddr-lat/min_freq not supported
2022-04-26 20:36:03.830 1279-1321/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [13, 12]
2022-04-26 20:36:03.830 1279-1321/? E/ANDR-PERF-UTIL: Failed to read /sys/class/devfreq/18321000.qcom,devfreq-l3:qcom,cpu0-cpu-l3-lat/max_freq
2022-04-26 20:36:03.830 1279-1321/? E/ANDR-PERF-UTIL: Failed to read /sys/class/devfreq/18321000.qcom,devfreq-l3:qcom,cpu4-cpu-l3-lat/max_freq
2022-04-26 20:36:03.830 1279-1321/? E/ANDR-PERF-UTIL: Failed to read /sys/class/devfreq/18321000.qcom,devfreq-l3:qcom,cpu7-cpu-l3-lat/max_freq
2022-04-26 20:36:03.836 31512-31512/? E/BlurUtils: fastBlurDirectly ratio=0.0   win=com.android.internal.policy.PhoneWindow@1b23b67
2022-04-26 20:36:03.854 31512-31603/? E/Launcher: notifyBackGestureStatus:run usingFsGesture=true   show=true   focus=false   pause=false
2022-04-26 20:36:03.878 3180-20223/? E/zeus-AndroidUtils-[pool-7-thread-2]: Get android id exception
    java.lang.SecurityException: getDeviceId: The user 10128 does not meet the requirements to access device identifiers.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceIdWithFeature(ITelephony.java:12085)
        at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:2003)
        at com.miui.zeus.utils.android.AndroidUtils.getIMEI(AndroidUtils.java:6)
        at com.miui.zeus.utils.android.AndroidUtils.getHashedIMEI(AndroidUtils.java:1)
        at d.a.b.c.a.a.d(ClientInfoHelper.java:15)
        at d.a.b.c.a.a.b(ClientInfoHelper.java:3)
        at com.xiaomi.ad.internal.server.c.f.c(InternalPreInstallServerV2.java:1)
        at com.xiaomi.ad.internal.server.c.f.a(InternalPreInstallServerV2.java:15)
        at com.xiaomi.ad.internal.server.c.i.a(ServerV30.java:6)
        at com.xiaomi.ad.internal.server.c.i.a(ServerV30.java:2)
        at com.xiaomi.ad.internal.server.c.f.a(InternalPreInstallServerV2.java:6)
        at com.miui.msa.internal.preinstall.v2.InternalPreInstallImplV2.loadDesktopRecommendAdInfoInner(InternalPreInstallImplV2.java:5)
        at com.miui.msa.internal.preinstall.v2.InternalPreInstallImplV2.access$000(InternalPreInstallImplV2.java:1)
        at com.miui.msa.internal.preinstall.v2.i.call(InternalPreInstallImplV2.java:2)
        at com.miui.msa.internal.preinstall.v2.i.call(InternalPreInstallImplV2.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
2022-04-26 20:36:03.976 1279-1279/? E/vendor.qti.hardware.perf-hal-service: Unknown params
2022-04-26 20:36:03.977 1279-1279/? E/vendor.qti.hardware.perf-hal-service: Unknown params
2022-04-26 20:36:04.019 22184-30849/? E/Market-CheckSingleAppUpdate: Index: 0, Size: 0
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.xiaomi.market.data.marketcall.CheckSingleAppUpdate.checkUpdate(CheckSingleAppUpdate.java:9)
        at com.xiaomi.market.data.marketcall.CheckSingleAppUpdate.access$000(CheckSingleAppUpdate.java:1)
        at com.xiaomi.market.data.marketcall.CheckSingleAppUpdate$CheckAppTask.call(CheckSingleAppUpdate.java:2)
        at com.xiaomi.market.data.marketcall.CheckSingleAppUpdate$CheckAppTask.call(CheckSingleAppUpdate.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.xiaomi.market.util.ThreadUtils$1.run(ThreadUtils.java:1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
2022-04-26 20:36:04.034 31512-20015/? E/Launcher.Transfer: transfer is closed
2022-04-26 20:36:04.134 31512-31512/? E/LauncherAnimationRunner: finish: mFinishRunnable.run
2022-04-26 20:36:04.135 31512-31512/? E/RotationHelper: setCurrentTransitionRequest: request=0
2022-04-26 20:36:04.138 1279-1279/? E/vendor.qti.hardware.perf-hal-service: Unknown params

**Comment by RealOnlyone** [comment]
这个问题是在新的自动化测试模块中引入的，现在已经修复了问题，在3.7.1及以后.

**Comment by RealOnlyone** [comment]
已解决

**Comment by RealOnlyone** [comment]
已解决
