### ISSUE TITLE
华为荣耀V10 ， Android9 ，获取GPS信息， requestLocationUpdates 代理导致崩溃

### ISSUE THREAD

**Issue by Allen-GaoYL** [didi/DoraemonKit#114]
Please complete the following informations.
> 华为荣耀V10 ， Android9 ，获取GPS信息，崩溃。
> Android 
Log:
Caused by: java.lang.NoSuchFieldException: No field mListener in class Landroid/location/LocationManager$ListenerTransport; (declaration of 'android.location.LocationManager$ListenerTransport' appears in /system/framework/framework.jar)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.didichuxing.doraemonkit.kit.gpsmock.LocationHookHandler.invoke(LocationHookHandler.java:40)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	... 22 more
java.lang.NoSuchFieldException: No field mListener in class Landroid/location/LocationManager$ListenerTransport; (declaration of 'android.location.LocationManager$ListenerTransport' appears in /system/framework/framework.jar)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.didichuxing.doraemonkit.kit.gpsmock.LocationHookHandler.invoke(LocationHookHandler.java:40)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy4.requestLocationUpdates(Unknown Source)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1155)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:709)
	at com.XXXXXX.app.widget.GPSUtils.getLngAndLat(GPSUtils.java:75)
	at com.XXXXXX.getGPSInfo(HJHomeScreenPage.java:1024)
	at com.XXXXXX.checkPermission(HJHomeScreenPage.java:1016)
	at com.XXXXXX.onCreate(HJHomeScreenPage.java:284)
	at android.app.Activity.performCreate(Activity.java:7436)
	at android.app.Activity.performCreate(Activity.java:7426)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7470)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by wanglikun7342** [comment]
后续修复这个问题

**Comment by wanglikun7342** [comment]
Android 1.1.3版本已经修复
