### ISSUE TITLE
点击沙盒游览>点击包名>点击lib(图标是个文件)>崩溃

### ISSUE THREAD

**Issue by LinXueyuanStdio** [didi/DoraemonKit#127]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）

正常显示

> 问题重现的步骤。（如有）

点击沙盒游览>点击包名>点击lib(图标是个文件)>崩溃

> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）

Android5.1，魅族MX5

> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
```
03-27 14:17:29.751 22329-22329/com.time.cat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.time.cat, PID: 22329
    java.lang.NullPointerException: Attempt to get length of null array
        at com.didichuxing.doraemonkit.kit.fileexplorer.FileExplorerFragment.getFileInfos(FileExplorerFragment.java:94)
        at com.didichuxing.doraemonkit.kit.fileexplorer.FileExplorerFragment.access$200(FileExplorerFragment.java:27)
        at com.didichuxing.doraemonkit.kit.fileexplorer.FileExplorerFragment$2.onViewClick(FileExplorerFragment.java:66)
        at com.didichuxing.doraemonkit.ui.fileexplorer.FileInfoAdapter$FileInfoViewHolder.onViewClick(FileInfoAdapter.java:83)
        at com.didichuxing.doraemonkit.ui.fileexplorer.FileInfoAdapter$FileInfoViewHolder.onViewClick(FileInfoAdapter.java:37)
        at com.didichuxing.doraemonkit.ui.widget.recyclerview.AbsViewBinder$1.onClick(AbsViewBinder.java:26)
        at android.view.View.performClick(View.java:4903)
        at android.view.View$PerformClick.run(View.java:20390)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5898)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
03-27 14:17:29.769 823-1884/? W/ActivityManager:   Force finishing activity 1 com.time.cat/com.didichuxing.doraemonkit.ui.UniversalActivity
03-27 14:17:29.772 823-1884/? W/ActivityManager: finishTopRunningActivityLocked , taskNdx is 2, activityNdx is 1
```

**Comment by wanglikun7342** [comment]
后续修复一下

**Comment by wanglikun7342** [comment]
Android 1.1.3版本已经修复
