### ISSUE TITLE
aspectjx编译的时候有点问题

### ISSUE THREAD

**Issue by yuanyang5917** [didi/DoraemonKit#187]
unable to write compilation result
java.util.zip.ZipException: duplicate entry: com/gem/tastyfood/fragments/UserPayPwdSecurityEmailFragment$AjcClosure1.class
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
	at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager$4.writeZipEntry(AjBuildManager.java:1181)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager$4.acceptResult(AjBuildManager.java:1118)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.acceptResult(AjPipeliningCompilerAdapter.java:460)
	at org.aspectj.ajdt.internal.compiler.WeaverAdapter.finishedWith(WeaverAdapter.java:225)
	at org.aspectj.ajdt.internal.compiler.WeaverAdapter.next(WeaverAdapter.java:130)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1170)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.weaveQueuedEntries(AjPipeliningCompilerAdapter.java:514)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.afterCompiling(AjPipeliningCompilerAdapter.java:375)
	at org.aspectj.ajdt.internal.compiler.CompilerAdapter.ajc$afterReturning$org_aspectj_ajdt_internal_compiler_CompilerAdapter$2$f9cc9ca0(CompilerAdapter.java:69)
	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:471)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1051)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:274)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:187)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
	at com.hujiang.gradle.plugin.android.aspectjx.internal.AJXTask.call(AJXTask.groovy:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by LinJZong** [comment]
UserPayPwdSecurityEmailFragment
这个类内是使用了httpurlconnection吗，能否把相关代码贴一下

**Comment by LinJZong** [comment]
看过好多用AspectJ的项目会报这个错，有一种可能是因为工程依赖的多个jar包中包含了同一个类名的文件，编译器会自动使用其中一个（一般是主工程内的同名文件），但AJ在做处理的时候会同时读取这两个类，倒是重复写入。可以全局搜索下是否有两个同名类UserPayPwdSecurityEmailFragment。

**Comment by yuanyang5917** [comment]
UserPayPwdSecurityEmailFragment只有一个的，这个远古项目用的是HttpClient，会导致问题么？
出现这个编译错误之后，打出的包，找不到application

**Comment by yuanyang5917** [comment]
我知道这个是可选的流量监控功能，去掉之后仍然会有一个问题：
java.lang.NoSuchMethodError: No static method aspectOf()Lcom/didichuxing/doraemonkit/DoraemonHooker; in class Lcom/didichuxing/doraemonkit/DoraemonHooker; or its super classes (declaration of 'com.didichuxing.doraemonkit.DoraemonHooker' appears in /data/app/com.gem.tastyfood-Zb3tX4YuOpAgu_oNH46OaQ==/split_lib_dependencies_apk.apk)
        at com.gem.tastyfood.AppContext.onCreate(AppContext.java:132)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1164)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6458)
        at android.app.ActivityThread.access$1400(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1805)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:217)
        at android.app.ActivityThread.main(ActivityThread.java:7376)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)

**Comment by yuanyang5917** [comment]
我知道这个是可选的流量监控功能，去掉之后仍然会有一个问题：
`java.lang.NoSuchMethodError: No static method aspectOf()Lcom/didichuxing/doraemonkit/DoraemonHooker; in class Lcom/didichuxing/doraemonkit/DoraemonHooker; or its super classes (declaration of 'com.didichuxing.doraemonkit.DoraemonHooker' appears in /data/app/com.gem.tastyfood-Zb3tX4YuOpAgu_oNH46OaQ==/split_lib_dependencies_apk.apk)
at com.gem.tastyfood.AppContext.onCreate(AppContext.java:132)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1164)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6458)
at android.app.ActivityThread.access$1400(ActivityThread.java:219)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1805)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:217)
at android.app.ActivityThread.main(ActivityThread.java:7376)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)`

**Comment by LinJZong** [comment]
是否使用了instant run?接的插件是这个吗
classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'
 找不到aspectOf方法是旧版本的插件用在新版本的代码上会有的问题，如果没使用instant run，那去掉插件引用后再clean一下代码应该就没问题了

**Comment by jokerzzzz** [comment]
我直接用签名打包也遇到了这个问题java.lang.NoSuchMethodError: No static method aspectOf()Lcom/didichuxing/doraemonkit/DoraemonHooker;

**Comment by LinJZong** [comment]
> UserPayPwdSecurityEmailFragment只有一个的，这个远古项目用的是HttpClient，会导致问题么？
> 出现这个编译错误之后，打出的包，找不到application

httpclient好像是会有问题的，我看了下httpclient的源码，里面会使用到HttpUrlConection，估计在AJ织入代码的时候会有点问题

**Comment by LinJZong** [comment]
> 我直接用签名打包也遇到了这个问题java.lang.NoSuchMethodError: No static method aspectOf()Lcom/didichuxing/doraemonkit/DoraemonHooker;

classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'
是用的这个版本的插件吗

**Comment by jokerzzzz** [comment]
> > 我直接用签名打包也遇到了这个问题java.lang.NoSuchMethodError: No static method aspectOf()Lcom/didichuxing/doraemonkit/DoraemonHooker;
> 
> classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'
> 是用的这个版本的插件吗

没使用插件，只是用了引用了基础包

**Comment by LinJZong** [comment]
> > > 我直接用签名打包也遇到了这个问题java.lang.NoSuchMethodError: No static method aspectOf()Lcom/didichuxing/doraemonkit/DoraemonHooker;
> > 
> > 
> > classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'
> > 是用的这个版本的插件吗
> 
> 没使用插件，只是用了引用了基础包

看看你的根目录的gradle的buildscript，怀疑是引用了其他插件包含了aspectj导致的，比如hugo之类的

**Comment by jokerzzzz** [comment]
> > > > 我直接用签名打包也遇到了这个问题java.lang.NoSuchMethodError: No static method aspectOf()Lcom/didichuxing/doraemonkit/DoraemonHooker;
> > > 
> > > 
> > > classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'
> > > 是用的这个版本的插件吗
> > 
> > 
> > 没使用插件，只是用了引用了基础包
> 
> 看看你的根目录的gradle的buildscript，怀疑是引用了其他插件包含了aspectj导致的，比如hugo之类的

对，用了hugo，是冲突了吗

**Comment by LinJZong** [comment]
> > > > > 我直接用签名打包也遇到了这个问题java.lang.NoSuchMethodError: No static method aspectOf()Lcom/didichuxing/doraemonkit/DoraemonHooker;
> > > > 
> > > > 
> > > > classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'
> > > > 是用的这个版本的插件吗
> > > 
> > > 
> > > 没使用插件，只是用了引用了基础包
> > 
> > 
> > 看看你的根目录的gradle的buildscript，怀疑是引用了其他插件包含了aspectj导致的，比如hugo之类的
> 
> 对，用了hugo，是冲突了吗

是的 hugo其实就是aspectj的一层封装，所以会把DoraemonHooker这个类内的AspectJ注解给解析了，然后hugo又不支持aar内的代码修改，导致DoraemonHooker这个类无法织入aspectOf等方法

**Comment by yuanyang5917** [comment]
感谢，我把神策注释掉也可以了

**Comment by LinJZong** [comment]
@yuanyang5917 
你的工程是否也使用了类似hugo之类包含AspectJ的插件，如果有两个AspectJ插件，导致代码被编织两遍，是可能出现你描述的问题的

**Comment by REBOOTERS** [comment]
> > > > > > 我直接用签名打包也遇到了这个问题java.lang.NoSuchMethodError: No static method aspectOf()Lcom/didichuxing/doraemonkit/DoraemonHooker;
> > > > > 
> > > > > 
> > > > > classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'
> > > > > 是用的这个版本的插件吗
> > > > 
> > > > 
> > > > 没使用插件，只是用了引用了基础包
> > > 
> > > 
> > > 看看你的根目录的gradle的buildscript，怀疑是引用了其他插件包含了aspectj导致的，比如hugo之类的
> > 
> > 
> > 对，用了hugo，是冲突了吗
> 
> 是的 hugo其实就是aspectj的一层封装，所以会把DoraemonHooker这个类内的AspectJ注解给解析了，然后hugo又不支持aar内的代码修改，导致DoraemonHooker这个类无法织入aspectOf等方法

想问一下，这个除了把 hugo 去掉，有其他解决方案吗？ （毕竟用hugo 很久了，代码里有很多 @DebugLog 的使用，一下子直接下掉真有点困难呢）

**Comment by LinJZong** [comment]
> 想问一下，这个除了把 hugo 去掉，有其他解决方案吗？ （毕竟用hugo 很久了，代码里有很多 @debuglog 的使用，一下子直接下掉真有点困难呢）

可以去掉hugo的插件引用，直接使用aspectjx的插件，然后在app的gradle内引用hugo-rutime这个库，这个库内包含了DebugLog的定义。
`    compile 'com.jakewharton.hugo:hugo-runtime:1.2.1'
`

**Comment by REBOOTERS** [comment]
> > 想问一下，这个除了把 hugo 去掉，有其他解决方案吗？ （毕竟用hugo 很久了，代码里有很多 @debuglog 的使用，一下子直接下掉真有点困难呢）
> 
> 可以去掉hugo的插件引用，直接使用aspectjx的插件，然后在app的gradle内引用hugo-runtime这个库，这个库内包含了DebugLog的定义。
> ` implementation 'com.jakewharton.hugo:hugo-runtime:1.2.1'`

OK，非常感谢。
