### ISSUE TITLE
在Android设备上浏览数据库表的时候，带有BLOB类型的不能浏览

### ISSUE THREAD

**Issue by aloneSingingStar** [didi/DoraemonKit#196]
在Android设备上浏览某张数据库表的时候，出现如下错误，其他表没问题。
android.database.sqlite.SQLiteException: unknown error (code 0): Unable to convert BLOB to string
        at android.database.CursorWindow.nativeGetString(Native Method)
        at android.database.CursorWindow.getString(CursorWindow.java:438)
        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
        at com.didichuxing.doraemonkit.util.DatabaseUtil.queryAll(DatabaseUtil.java:46)
        at com.didichuxing.doraemonkit.kit.fileexplorer.DatabaseDetailFragment$2.onItemClick(DatabaseDetailFragment.java:77)
        at android.widget.AdapterView.performItemClick(AdapterView.java:305)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3057)
        at android.widget.AbsListView$3.run(AbsListView.java:3864)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5259)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)

**Comment by Chinnko** [comment]
数据库表方便提供给我吗

**Comment by Chinnko** [comment]
近期修复
