### ISSUE TITLE
RN页面的布局边框功能crash

### ISSUE THREAD

**Issue by zd1471278687** [didi/DoraemonKit#199]
RN页面点击视觉工具-布局边框功能，直接崩溃，崩溃日志如下

java.lang.UnsupportedOperationException: This method is not supported for ReactViewGroup instances
        at com.facebook.react.views.view.ReactViewGroup.setBackground(ReactViewGroup.java:163)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.replaceDrawable(ViewBorderFrameLayout.java:90)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:48)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:52)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:52)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:52)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:52)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:52)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:52)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:52)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.onLayout(ViewBorderFrameLayout.java:40)
        at android.view.View.layout(View.java:15918)
        at android.view.ViewGroup.layout(ViewGroup.java:5119)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:633)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:568)
        at android.view.View.layout(View.java:15918)
        at android.view.ViewGroup.layout(ViewGroup.java:5119)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:633)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:568)
        at android.view.View.layout(View.java:15918)
        at android.view.ViewGroup.layout(ViewGroup.java:5119)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2553)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2243)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6715)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
        at android.view.Choreographer.doCallbacks(Choreographer.java:603)
        at android.view.Choreographer.doFrame(Choreographer.java:572)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:5819)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:998)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)

**Comment by yixiangboy** [comment]
收到 下个版本修复

**Comment by wanglikun7342** [comment]
1.2.0版本已经修复了这个问题
