### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by LiWeiQiangAndroid** [didi/DoraemonKit#226]
E/Reflection:  reflect  bootstrap  failed:
        java.lang.reflect.InvocationTargetException
                at  java.lang.reflect.Method.invoke(Native  Method)
                at  me.weishu.reflection.Reflection.<clinit>(Reflection.java:32)
                at  com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26)
                at  com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93)
                at  com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71)
                at  com.khmer.fm.MainApplication.onCreate(MainApplication.java:101)
                at  android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                at  android.app.ActivityThread.handleBindApplication(ActivityThread.java:4806)
                at  de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native  Method)
                at  de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
                at  android.app.ActivityThread.handleBindApplication(<Xposed>)
                at  android.app.ActivityThread.access$1600(ActivityThread.java:154)
                at  android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
                at  android.os.Handler.dispatchMessage(Handler.java:102)
                at  android.os.Looper.loop(Looper.java:234)
                at  android.app.ActivityThread.main(ActivityThread.java:5526)
                at  java.lang.reflect.Method.invoke(Native  Method)
                at  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                at  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                at  de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
          Caused  by:  java.lang.NoSuchMethodException:  setHiddenApiExemptions  [class  [Ljava.lang.String;]
                at  java.lang.Class.getMethod(Class.java:624)
                at  java.lang.Class.getDeclaredMethod(Class.java:586)
                at  java.lang.reflect.Method.invoke(Native  Method) 
                at  me.weishu.reflection.Reflection.<clinit>(Reflection.java:32) 
                at  com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26) 
                at  com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93) 
                at  com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71) 
                at  com.khmer.fm.MainApplication.onCreate(MainApplication.java:101) 
                at  android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014) 
                at  android.app.ActivityThread.handleBindApplication(ActivityThread.java:4806) 
                at  de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native  Method) 
                at  de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740) 
                at  android.app.ActivityThread.handleBindApplication(<Xposed>) 
                at  android.app.ActivityThread.access$1600(ActivityThread.java:154) 
                at  android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452) 
                at  android.os.Handler.dispatchMessa ge(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:234) 
        at android.app.ActivityThread.main(ActivityThread.java:5526) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
06-24 16:44:32.761 17015-17015/com.khmer.fm E/AndroidRuntime: FATAL EXCEPTION: main

//DoraemonKit.install(this);

港版机型平台：Sony E6883 Android 6.0.1, API 23
Android启动闪退

**Comment by LinJZong** [comment]
这个日志是catch住之后主动打印的，还有其他日志吗

**Comment by LiWeiQiangAndroid** [comment]
是的、下面是再次捕获异常信息，机子装了Xposed的

06-24 20:47:44.469 26379-26379/com.khmer.fm E/Reflection: reflect bootstrap failed:
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32)
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26)
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93)
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71)
        at com.khmer.fm.MainApplication.onCreate(MainApplication.java:108)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4806)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
        at android.app.ActivityThread.handleBindApplication(<Xposed>)
        at android.app.ActivityThread.access$1600(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:234)
        at android.app.ActivityThread.main(ActivityThread.java:5526)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
     Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
        at java.lang.Class.getMethod(Class.java:624)
        at java.lang.Class.getDeclaredMethod(Class.java:586)
        at java.lang.reflect.Method.invoke(Native Method) 
        at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32) 
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26) 
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93) 
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71) 
        at com.khmer.fm.MainApplication.onCreate(MainApplication.java:108) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4806) 
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740) 
        at android.app.ActivityThread.handleBindApplication(<Xposed>) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:234) 
        at android.app.ActivityThread.main(ActivityThread.java:5526) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

**Comment by LinJZong** [comment]
看日志没什么问题，这个是主动catch住自己打出来的日志，不会造成崩溃才对，如果有崩溃了，应该是其他方面引起的

**Comment by LiWeiQiangAndroid** [comment]
是的，部分机型会闪退

**Comment by laro67** [comment]
[अवेसो।3](url)

**Comment by wanglikun7342** [comment]
1.2.0已经去掉了这个日志信息
