### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by PengZeHai** [didi/DoraemonKit#228]
有这个异常
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32)
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26)
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93)
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71)

**Comment by LinJZong** [comment]
这个是DoKit主动catch住自己打出来的日志,没其他影响
