### ISSUE TITLE
Reflection: reflect bootstrap failed:     java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by martin-huang** [didi/DoraemonKit#230]
Please complete the following informations.
> initDoraemnKit
> initDoraemnKit
> Android
>  java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32)
        at me.weishu.reflection.Reflection.unseal(Unknown Source:0)
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26)
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93)
出现了这个bug 是什么原因呢？？？

**Comment by wanglikun7342** [comment]
1.2.0已经去掉了这个日志信息
