### ISSUE TITLE
android 8.0 install crash 

### ISSUE THREAD

**Issue by GJson** [didi/DoraemonKit#237]
![image](https://user-images.githubusercontent.com/8514355/61264158-20f40a80-a7be-11e9-87b7-6c0046abaabf.png)
![image](https://user-images.githubusercontent.com/8514355/61264171-2c473600-a7be-11e9-8e57-da7911b92786.png)

**Comment by GJson** [comment]
Android SDK :1.1.8

**Comment by GJson** [comment]
com.didichuxing.doraemonkit:doraemonkit:1.1.8

**Comment by wanglikun7342** [comment]
有没有详细的啊

**Comment by dengyuhan** [comment]
我之前也遇到了，Demo卸载重装可以重现
```
2019-07-17 18:14:25.738 13685-13685/com.didichuxing.doraemondemo E/Reflection: reflect bootstrap failed:
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32)
        at me.weishu.reflection.Reflection.unseal(Reflection.java:50)
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26)
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93)
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71)
        at com.didichuxing.doraemondemo.App.onCreate_aroundBody0(App.java:18)
        at com.didichuxing.doraemondemo.App$AjcClosure1.run(App.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at parking.didi.com.aop.DoraemonHooker.install(DoraemonHooker.java:24)
        at com.didichuxing.doraemondemo.App.onCreate(App.java:17)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5877)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
     Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at java.lang.reflect.Method.invoke(Native Method) 
        at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32) 
        at me.weishu.reflection.Reflection.unseal(Reflection.java:50) 
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26) 
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93) 
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71) 
        at com.didichuxing.doraemondemo.App.onCreate_aroundBody0(App.java:18) 
        at com.didichuxing.doraemondemo.App$AjcClosure1.run(App.java:1) 
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) 
        at parking.didi.com.aop.DoraemonHooker.install(DoraemonHooker.java:24) 
        at com.didichuxing.doraemondemo.App.onCreate(App.java:17) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5877) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:173) 
        at android.app.ActivityThread.main(ActivityThread.java:6698) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782) 
```

**Comment by LinJZong** [comment]
> 我之前也遇到了，Demo卸载重装可以重现
> 
> ```
> 2019-07-17 18:14:25.738 13685-13685/com.didichuxing.doraemondemo E/Reflection: reflect bootstrap failed:
>     java.lang.reflect.InvocationTargetException
>         at java.lang.reflect.Method.invoke(Native Method)
>         at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32)
>         at me.weishu.reflection.Reflection.unseal(Reflection.java:50)
>         at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26)
>         at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93)
>         at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71)
>         at com.didichuxing.doraemondemo.App.onCreate_aroundBody0(App.java:18)
>         at com.didichuxing.doraemondemo.App$AjcClosure1.run(App.java:1)
>         at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
>         at parking.didi.com.aop.DoraemonHooker.install(DoraemonHooker.java:24)
>         at com.didichuxing.doraemondemo.App.onCreate(App.java:17)
>         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5877)
>         at android.app.ActivityThread.-wrap1(Unknown Source:0)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
>         at android.os.Handler.dispatchMessage(Handler.java:105)
>         at android.os.Looper.loop(Looper.java:173)
>         at android.app.ActivityThread.main(ActivityThread.java:6698)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
>      Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
>         at java.lang.Class.getMethod(Class.java:2068)
>         at java.lang.Class.getDeclaredMethod(Class.java:2047)
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32) 
>         at me.weishu.reflection.Reflection.unseal(Reflection.java:50) 
>         at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26) 
>         at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93) 
>         at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71) 
>         at com.didichuxing.doraemondemo.App.onCreate_aroundBody0(App.java:18) 
>         at com.didichuxing.doraemondemo.App$AjcClosure1.run(App.java:1) 
>         at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) 
>         at parking.didi.com.aop.DoraemonHooker.install(DoraemonHooker.java:24) 
>         at com.didichuxing.doraemondemo.App.onCreate(App.java:17) 
>         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119) 
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5877) 
>         at android.app.ActivityThread.-wrap1(Unknown Source:0) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690) 
>         at android.os.Handler.dispatchMessage(Handler.java:105) 
>         at android.os.Looper.loop(Looper.java:173) 
>         at android.app.ActivityThread.main(ActivityThread.java:6698) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782) 
> ```

会引起crash吗，这个Log只是sdk内部打印的错误日志，如果有crash麻烦多截一点日志，看看是否是其他地方引起的

**Comment by wanglikun7342** [comment]
1.2.0已经去掉这个日志信息，
