### ISSUE TITLE
This method is not supported for ReactViewGroup instances

### ISSUE THREAD

**Issue by LiWeiQiangAndroid** [didi/DoraemonKit#246]
RN 安卓打开布局边框闪退

2019-08-03 14:25:14.221 22646-22646/com.xxxx.user E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.beefood.user, PID: 22646
    java.lang.UnsupportedOperationException: This method is not supported for ReactViewGroup instances
        at com.facebook.react.views.view.ReactViewGroup.setBackground(ReactViewGroup.java:180)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.replaceDrawable(ViewBorderFrameLayout.java:90)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:48)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:52)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:52)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:52)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:52)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:52)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.traverseChild(ViewBorderFrameLayout.java:52)
        at com.didichuxing.doraemonkit.ui.layoutborder.ViewBorderFrameLayout.onLayout(ViewBorderFrameLayout.java:40)
        at android.view.View.layout(View.java:17551)
        at android.view.ViewGroup.layout(ViewGroup.java:5614)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17551)
        at android.view.ViewGroup.layout(ViewGroup.java:5614)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:727)
        at android.view.View.layout(View.java:17551)
        at android.view.ViewGroup.layout(ViewGroup.java:5614)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2386)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2113)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1290)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6400)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
        at android.view.Choreographer.doCallbacks(Choreographer.java:685)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6358)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

布局边框不支持ReactViewGroup
点击布局边框即闪退

**Comment by wanglikun7342** [comment]
1.2.0版本已经修复了这个问题
