### ISSUE TITLE
帧率检测android 帧率 cpu 内存 无法查看 华为 lld-al00

### ISSUE THREAD

**Issue by heyangJob** [didi/DoraemonKit#253]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
点击上面三个都崩溃
Android 8.0  集成1.2.0

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
                                                                                        at com.didichuxing.doraemonkit.kit.common.PerformanceDataManager.init(PerformanceDataManager.java:165)
                                                                                        at com.didichuxing.doraemonkit.ui.realtime.RealTimeChartIconPage.onCreate(RealTimeChartIconPage.java:44)
                                                                                        at com.didichuxing.doraemonkit.ui.base.BaseFloatPage.performCreate(BaseFloatPage.java:41)
                                                                                        at com.didichuxing.doraemonkit.ui.base.FloatPageManager.add(FloatPageManager.java:67)
                                                                                        at com.didichuxing.doraemonkit.ui.realtime.RealTimeChartIconPage.openChartIconPage(RealTimeChartIconPage.java:73)
                                                                                        at com.didichuxing.doraemonkit.ui.realtime.RealTimeChartPage.openChartPage(RealTimeChartPage.java:87)
                                                                                        at com.didichuxing.doraemonkit.kit.parameter.AbsParameterFragment.openChartPage(AbsParameterFragment.java:60)
                                                                                        at com.didichuxing.doraemonkit.kit.parameter.frameInfo.FrameInfoFragment.startMonitor(FrameInfoFragment.java:75)
                                                                                        at com.didichuxing.doraemonkit.kit.parameter.frameInfo.FrameInfoFragment.access$000(FrameInfoFragment.java:22)
                                                                                        at com.didichuxing.doraemonkit.kit.parameter.frameInfo.FrameInfoFragment$1.onSettingItemSwitch(FrameInfoFragment.java:48)
                                                                                        at com.didichuxing.doraemonkit.kit.parameter.AbsParameterFragment$2.onSettingItemSwitch(AbsParameterFragment.java:94)
                                                                                        at com.didichuxing.doraemonkit.ui.setting.SettingItemAdapter$SettingItemViewHolder$1.onCheckedChanged(SettingItemAdapter.java:67)
                                                                                        at android.widget.CompoundButton.setChecked(CompoundButton.java:172)
                                                                                        at android.widget.CompoundButton.toggle(CompoundButton.java:128)
                                                                                        at android.widget.CompoundButton.performClick(CompoundButton.java:133)
                                                                                        at android.view.View$PerformClick.run(View.java:24931)
                                                                                        at android.os.Handler.handleCallback(Handler.java:808)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                        at android.os.Looper.loop(Looper.java:166)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:7529)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

reflect bootstrap failed:
                                                                                java.lang.reflect.InvocationTargetException
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32)
                                                                                    at me.weishu.reflection.Reflection.unseal(Reflection.java:50)
                                                                                    at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26)
                                                                                    at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93)
                                                                                    at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71)
                                                                                    at com.star.mobile.video.application.STApp.onCreate(STApp.java:54)
                                                                                    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)
                                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619)
                                                                                    at android.app.ActivityThread.-wrap2(Unknown Source:0)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:108)
                                                                                    at android.os.Looper.loop(Looper.java:166)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7529)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
                                                                                 Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
                                                                                    at java.lang.Class.getMethod(Class.java:2068)
                                                                                    at java.lang.Class.getDeclaredMethod(Class.java:2047)
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32) 
                                                                                    at me.weishu.reflection.Reflection.unseal(Reflection.java:50) 
                                                                                    at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26) 
                                                                                    at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93) 
                                                                                    at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71) 
                                                                                    at com.star.mobile.video.application.STApp.onCreate(STApp.java:54) 
                                                                                    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122) 
                                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619) 
                                                                                    at android.app.ActivityThread.-wrap2(Unknown Source:0) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:108) 
                                                                                    at android.os.Looper.loop(Looper.java:166) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7529) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by wanglikun7342** [comment]
1.2.1版本修复了这个问题

**Comment by heyangJob** [comment]
使用新的出现java.lang.NoSuchMethodException: setHiddenApiExemptions
 reflect bootstrap failed:
                                               java.lang.reflect.InvocationTargetException
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32)
                                                   at me.weishu.reflection.Reflection.unseal(Reflection.java:50)
                                                   at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26)
                                                   at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93)
                                                   at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71)
                                                   at com.star.mobile.video.application.STApp.onCreate(STApp.java:54)
                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)
                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619)
                                                   at android.app.ActivityThread.-wrap2(Unknown Source:0)
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
                                                   at android.os.Handler.dispatchMessage(Handler.java:108)
                                                   at android.os.Looper.loop(Looper.java:166)
                                                   at android.app.ActivityThread.main(ActivityThread.java:7529)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
                                                Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
                                                   at java.lang.Class.getMethod(Class.java:2068)
                                                   at java.lang.Class.getDeclaredMethod(Class.java:2047)
                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                   at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32) 
                                                   at me.weishu.reflection.Reflection.unseal(Reflection.java:50) 
                                                   at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26) 
                                                   at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93) 
                                                   at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71) 
                                                   at com.star.mobile.video.application.STApp.onCreate(STApp.java:54) 
                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122) 
                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619) 
                                                   at android.app.ActivityThread.-wrap2(Unknown Source:0) 
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
                                                   at android.os.Handler.dispatchMessage(Handler.java:108) 
                                                   at android.os.Looper.loop(Looper.java:166) 
                                                   at android.app.ActivityThread.main(ActivityThread.java:7529) 
                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
