### ISSUE TITLE
java.lang.NoSuchMethodException: setHiddenApiExemptions

### ISSUE THREAD

**Issue by heyangJob** [didi/DoraemonKit#254]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

Android 8.0  华为LLD-AL00
使用最新的1.2.1

 reflect bootstrap failed:
                                               java.lang.reflect.InvocationTargetException
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32)
                                                   at me.weishu.reflection.Reflection.unseal(Reflection.java:50)
                                                   at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26)
                                                   at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93)
                                                   at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71)
                                                   at com.star.mobile.video.application.STApp.onCreate(STApp.java:54)
                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)
                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619)
                                                   at android.app.ActivityThread.-wrap2(Unknown Source:0)
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
                                                   at android.os.Handler.dispatchMessage(Handler.java:108)
                                                   at android.os.Looper.loop(Looper.java:166)
                                                   at android.app.ActivityThread.main(ActivityThread.java:7529)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
                                                Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
                                                   at java.lang.Class.getMethod(Class.java:2068)
                                                   at java.lang.Class.getDeclaredMethod(Class.java:2047)
                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                   at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32) 
                                                   at me.weishu.reflection.Reflection.unseal(Reflection.java:50) 
                                                   at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26) 
                                                   at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93) 
                                                   at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71) 
                                                   at com.star.mobile.video.application.STApp.onCreate(STApp.java:54) 
                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122) 
                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619) 
                                                   at android.app.ActivityThread.-wrap2(Unknown Source:0) 
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
                                                   at android.os.Handler.dispatchMessage(Handler.java:108) 
                                                   at android.os.Looper.loop(Looper.java:166) 
                                                   at android.app.ActivityThread.main(ActivityThread.java:7529) 
                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by heyangJob** [comment]
应该是rom改了没有这个字段了，没兼容

**Comment by caiyoufei** [comment]
同上：
机型：魅蓝5S，安卓6.0
![image](https://user-images.githubusercontent.com/11989916/66448991-b16c7f00-ea7d-11e9-8dfd-90f5cb6e32bf.png)

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> Android 8.0 华为LLD-AL00
> 使用最新的1.2.1
> 
> reflect bootstrap failed:
> java.lang.reflect.InvocationTargetException
> at java.lang.reflect.Method.invoke(Native Method)
> at me.weishu.reflection.Reflection.(Reflection.java:32)
> at me.weishu.reflection.Reflection.unseal(Reflection.java:50)
> at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26)
> at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93)
> at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71)
> at com.star.mobile.video.application.STApp.onCreate(STApp.java:54)
> at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)
> at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619)
> at android.app.ActivityThread.-wrap2(Unknown Source:0)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
> at android.os.Handler.dispatchMessage(Handler.java:108)
> at android.os.Looper.loop(Looper.java:166)
> at android.app.ActivityThread.main(ActivityThread.java:7529)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
> Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
> at java.lang.Class.getMethod(Class.java:2068)
> at java.lang.Class.getDeclaredMethod(Class.java:2047)
> at java.lang.reflect.Method.invoke(Native Method) 
> at me.weishu.reflection.Reflection.(Reflection.java:32) 
> at me.weishu.reflection.Reflection.unseal(Reflection.java:50) 
> at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26) 
> at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93) 
> at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71) 
> at com.star.mobile.video.application.STApp.onCreate(STApp.java:54) 
> at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122) 
> at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619) 
> at android.app.ActivityThread.-wrap2(Unknown Source:0) 
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
> at android.os.Handler.dispatchMessage(Handler.java:108) 
> at android.os.Looper.loop(Looper.java:166) 
> at android.app.ActivityThread.main(ActivityThread.java:7529) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

这个问题其实我们内部使用过程中也发现了，这是我们使用了一个第三方库来绕过系统隐藏api，该库内部抛出的异常，但是不会影响功能使用，暂时也没发现造成崩溃现象，所以大家暂时可以忽略这条日志，后期找到更好的方法的话我们会进行替换。
