### ISSUE TITLE
安卓点击缓存崩溃

### ISSUE THREAD

**Issue by KaelInvoker** [didi/DoraemonKit#264]
依赖版本：com.didichuxing.doraemonkit:doraemonkit-weex:1.0.0  
 android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ContextImpl.startActivity(ContextImpl.java:922)
        at android.app.ContextImpl.startActivity(ContextImpl.java:898)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:389)
        at com.didichuxing.doraemonkit.weex.common.DKCommonActivity.startWith(DKCommonActivity.java:22)
        at com.didichuxing.doraemonkit.weex.storage.StorageKit.onClick(StorageKit.java:33)
        at com.didichuxing.doraemonkit.ui.kit.KitAdapter$KitViewHolder.onViewClick(KitAdapter.java:60)
        at com.didichuxing.doraemonkit.ui.kit.KitAdapter$KitViewHolder.onViewClick(KitAdapter.java:36)
        at com.didichuxing.doraemonkit.ui.widget.recyclerview.AbsViewBinder$1.onClick(AbsViewBinder.java:26)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25919)
        at android.os.Handler.handleCallback(Handler.java:873)

**Comment by KaelInvoker** [comment]
点击业务专区一整栏按钮都是这么错误

**Comment by wanglikun7342** [comment]
weex版本 1.0.1版本已经修复
com.didichuxing.doraemonkit:doraemonkit-weex:1.0.1
