### ISSUE TITLE
在Activity的点击事件回调里面install，不出现悬浮窗，退出当前Activity的时候会闪现立马消失，切换任意Activity会闪现立马消失

### ISSUE THREAD

**Issue by Android-xiaole** [didi/DoraemonKit#266]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。
-希望可以通过点击事件进行注册，例如连续点击进入开发者模式的效果
但实际效果，在点击事件里面注册时候，暂时不会出现悬浮窗，切换的时候会闪现一下后立马消失，但是如果在Activity和Application的onCreate里面注册没有问题

> 问题重现的步骤。
-在任意Activity里面通过点击事件进行注册

> Android 还是 iOS？系统版本是多少？手机品牌是什么？
-Android 小米5X刷的android8.0.0谷歌源生系统（别的手测试也是相同问题例如OPPO R17 android 8.1.0）

> 其他的错误信息和堆栈信息如果有也可以一并提供出来。
-2019-08-21 17:34:33.650 21705-21705/com.jj.mz E/Reflection: reflect bootstrap failed:
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32)
        at me.weishu.reflection.Reflection.unseal(Reflection.java:50)
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26)
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93)
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71)
        at com.jj.comics.ui.mine.settings.AboutActivity.showChannel(AboutActivity.java:46)
        at com.jj.comics.ui.mine.settings.AboutActivity_ViewBinding$2.onLongClick(AboutActivity_ViewBinding.java:42)
        at android.view.View.performLongClickInternal(View.java:6336)
        at android.view.View.performLongClick(View.java:6294)
        at android.view.View.performLongClick(View.java:6312)
        at android.view.View$CheckForLongPress.run(View.java:24666)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:172)
        at android.app.ActivityThread.main(ActivityThread.java:6637)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
     Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at java.lang.reflect.Method.invoke(Native Method) 
        at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32) 
        at me.weishu.reflection.Reflection.unseal(Reflection.java:50) 
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26) 
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93) 
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71) 
        at com.jj.comics.ui.mine.settings.AboutActivity.showChannel(AboutActivity.java:46) 
        at com.jj.comics.ui.mine.settings.AboutActivity_ViewBinding$2.onLongClick(AboutActivity_ViewBinding.java:42) 
        at android.view.View.performLongClickInternal(View.java:6336) 
        at android.view.View.performLongClick(View.java:6294) 
        at android.view.View.performLongClick(View.java:6312) 
        at android.view.View$CheckForLongPress.run(View.java:24666) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:172) 
        at android.app.ActivityThread.main(ActivityThread.java:6637) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。
> > -希望可以通过点击事件进行注册，例如连续点击进入开发者模式的效果
> > 但实际效果，在点击事件里面注册时候，暂时不会出现悬浮窗，切换的时候会闪现一下后立马消失，但是如果在Activity和Application的onCreate里面注册没有问题
> 
> > 问题重现的步骤。
> > -在任意Activity里面通过点击事件进行注册
> 
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？
> > -Android 小米5X刷的android8.0.0谷歌源生系统（别的手测试也是相同问题例如OPPO R17 android 8.1.0）
> 
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。
> > -2019-08-21 17:34:33.650 21705-21705/com.jj.mz E/Reflection: reflect bootstrap failed:
> > java.lang.reflect.InvocationTargetException
> > at java.lang.reflect.Method.invoke(Native Method)
> > at me.weishu.reflection.Reflection.(Reflection.java:32)
> > at me.weishu.reflection.Reflection.unseal(Reflection.java:50)
> > at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26)
> > at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93)
> > at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71)
> > at com.jj.comics.ui.mine.settings.AboutActivity.showChannel(AboutActivity.java:46)
> > at com.jj.comics.ui.mine.settings.AboutActivity_ViewBinding$2.onLongClick(AboutActivity_ViewBinding.java:42)
> > at android.view.View.performLongClickInternal(View.java:6336)
> > at android.view.View.performLongClick(View.java:6294)
> > at android.view.View.performLongClick(View.java:6312)
> > at android.view.View$CheckForLongPress.run(View.java:24666)
> > at android.os.Handler.handleCallback(Handler.java:789)
> > at android.os.Handler.dispatchMessage(Handler.java:98)
> > at android.os.Looper.loop(Looper.java:172)
> > at android.app.ActivityThread.main(ActivityThread.java:6637)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
> > at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
> > Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
> > at java.lang.Class.getMethod(Class.java:2068)
> > at java.lang.Class.getDeclaredMethod(Class.java:2047)
> > at java.lang.reflect.Method.invoke(Native Method) 
> > at me.weishu.reflection.Reflection.(Reflection.java:32) 
> > at me.weishu.reflection.Reflection.unseal(Reflection.java:50) 
> > at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.HandlerHooker.doHook(HandlerHooker.java:26) 
> > at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:93) 
> > at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:71) 
> > at com.jj.comics.ui.mine.settings.AboutActivity.showChannel(AboutActivity.java:46) 
> > at com.jj.comics.ui.mine.settings.AboutActivity_ViewBinding$2.onLongClick(AboutActivity_ViewBinding.java:42) 
> > at android.view.View.performLongClickInternal(View.java:6336) 
> > at android.view.View.performLongClick(View.java:6294) 
> > at android.view.View.performLongClick(View.java:6312) 
> > at android.view.View$CheckForLongPress.run(View.java:24666) 
> > at android.os.Handler.handleCallback(Handler.java:789) 
> > at android.os.Handler.dispatchMessage(Handler.java:98) 
> > at android.os.Looper.loop(Looper.java:172) 
> > at android.app.ActivityThread.main(ActivityThread.java:6637) 
> > at java.lang.reflect.Method.invoke(Native Method) 
> > at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
> > at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

你好 我们dokit的机制是在application启动的时候通过hook 系统api的方式实现统一的拦截功能，如果install延迟，可能并不能hook 成果，最好请按照文档提供的方式来介入dokit sdk，谢谢。
