### ISSUE TITLE
 Caused by: java.lang.IllegalAccessException: Class java.lang.Class<com.didichuxing.doraemonkit.kit.gpsmock.LocationHooker$RemoveUpdatesMethodHandler> cannot access private  field android.location.LocationListener 

### ISSUE THREAD

**Issue by huangjim** [didi/DoraemonKit#278]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

华为手机ALP-L29，Android系统9.0 打开就报错
用的最新的1.2.1

 UncaughtException detected: java.lang.reflect.UndeclaredThrowableException
        at $Proxy5.removeUpdates(Unknown Source)
        at android.location.LocationManager.removeUpdates(LocationManager.java:1185)
        at xx.xx.service.LocationService$1.onLocationChanged(LocationService.java:114)
        at com.didichuxing.doraemonkit.kit.gpsmock.LocationHooker$RequestLocationUpdatesMethodHandler$1.onLocationChanged(LocationHooker.java:117)
        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:518)
        at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:304)
        at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.lang.IllegalAccessException: Class java.lang.Class<com.didichuxing.doraemonkit.kit.gpsmock.LocationHooker$RemoveUpdatesMethodHandler> cannot access private  field android.location.LocationListener android.location.LocationManager$ListenerTransport.mListener of class java.lang.Class<android.location.LocationManager$ListenerTransport>

看你们源码有这段
`
    private class RemoveUpdatesMethodHandler implements MethodHandler {
        @Override
        public Object onInvoke(Object originService, Object proxy, Method method, Object[] args) throws InvocationTargetException, IllegalAccessException, NoSuchFieldException {
            Field mListenerField = args[0].getClass().getDeclaredField("mListener");
            mListeners.remove(mListenerField.get(args[0]));
            return null;
        }
    }
`
我们项目也用到了
`
 mLocationManager.removeUpdates(mLocationListener);
`
是什么原因产生的

**Comment by RuffianZhong** [comment]
HUAWEI  LLD-AL20  8.0.0 
版本1.2.1，同样错误一路狂崩~~

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。（如有）
> > 问题重现的步骤。（如有）
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 
> 华为手机ALP-L29，Android系统9.0 打开就报错
> 用的最新的1.2.1
> 
> UncaughtException detected: java.lang.reflect.UndeclaredThrowableException
> at $Proxy5.removeUpdates(Unknown Source)
> at android.location.LocationManager.removeUpdates(LocationManager.java:1185)
> at xx.xx.service.LocationService$1.onLocationChanged(LocationService.java:114)
> at com.didichuxing.doraemonkit.kit.gpsmock.LocationHooker$RequestLocationUpdatesMethodHandler$1.onLocationChanged(LocationHooker.java:117)
> at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:518)
> at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:304)
> at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:326)
> at android.os.Handler.dispatchMessage(Handler.java:109)
> at android.os.Looper.loop(Looper.java:207)
> at android.app.ActivityThread.main(ActivityThread.java:7470)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
> Caused by: java.lang.IllegalAccessException: Class java.lang.Class<com.didichuxing.doraemonkit.kit.gpsmock.LocationHooker$RemoveUpdatesMethodHandler> cannot access private field android.location.LocationListener android.location.LocationManager$ListenerTransport.mListener of class java.lang.Class<android.location.LocationManager$ListenerTransport>
> 
> 看你们源码有这段
> `private class RemoveUpdatesMethodHandler implements MethodHandler { @Override public Object onInvoke(Object originService, Object proxy, Method method, Object[] args) throws InvocationTargetException, IllegalAccessException, NoSuchFieldException { Field mListenerField = args[0].getClass().getDeclaredField("mListener"); mListeners.remove(mListenerField.get(args[0])); return null; } }`
> 我们项目也用到了
> `mLocationManager.removeUpdates(mLocationListener);`
> 是什么原因产生的

已定位问题 下个版本会修复
