### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup

### ISSUE THREAD

**Issue by jhwsx** [didi/DoraemonKit#328]
# Version:
```
    debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:2.0.1'
    releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.0.1'
```
# log:
```text
    java.lang.RuntimeException: Unable to resume activity {com.prdsff.veryclean/com.prdsff.veryclean.whatsapp.WhatsAppCleanActivity}: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3139)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3170)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1420)
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:38)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5621)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
     Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
        at android.view.ViewGroup.addView(ViewGroup.java:4154)
        at android.view.ViewGroup.addView(ViewGroup.java:4134)
        at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.attach(NormalDokitViewManager.java:203)
        at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.resumeAndAttachDokitViews(NormalDokitViewManager.java:145)
        at com.didichuxing.doraemonkit.ui.base.DokitViewManager.resumeAndAttachDokitViews(DokitViewManager.java:120)
        at com.didichuxing.doraemonkit.DoraemonKit.resumeAndAttachDokitViews(DoraemonKit.java:491)
        at com.didichuxing.doraemonkit.DoraemonKit.access$300(DoraemonKit.java:74)
        at com.didichuxing.doraemonkit.DoraemonKit$2.onActivityResumed(DoraemonKit.java:211)
        at android.app.Application.dispatchActivityResumed(Application.java:214)
        at android.app.Activity.onResume(Activity.java:1245)
        at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:456)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1266)
        at android.app.Activity.performResume(Activity.java:6446)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3129)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3170) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1420) 
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:38) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:150) 
        at android.app.ActivityThread.main(ActivityThread.java:5621) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
```
# Step:
After I exit color picker, this issue happens.

**Comment by jtsky** [comment]
> NormalDokitViewManager

fixed ,thanks

**Comment by YummyLau** [comment]
依赖为：'com.didichuxing.doraemonkit:doraemonkit:2.0.1'
机型：BLN-AL20
系统：Android 8.0

java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
	at android.view.ViewGroup.addView(ViewGroup.java:4799)
	at android.view.ViewGroup.addView(ViewGroup.java:4779)
	at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.attach(Unknown Source:207)
	at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.resumeAndAttachDokitViews(Unknown Source:320)
	at com.didichuxing.doraemonkit.ui.base.DokitViewManager.resumeAndAttachDokitViews(Unknown Source:2)
	at com.didichuxing.doraemonkit.DoraemonKit.resumeAndAttachDokitViews(Unknown Source:4)
	at com.didichuxing.doraemonkit.DoraemonKit.access$300(Unknown Source:0)
	at com.didichuxing.doraemonkit.DoraemonKit$2.onActivityResumed(Unknown Source:26)
	at android.app.Application.dispatchActivityResumed(Application.java:227)
	at android.app.Activity.onResume(Activity.java:1415)
	at android.support.v4.app.FragmentActivity.onResume(Unknown Source:0)
	at im.yixin.gl.log.page.view.LogActivity.onResume(Unknown Source:0)
	at im.yixin.gl.log.page.view.LogSwipeBackActivity.onResume(Unknown Source:0)
	at com.netease.gl.ui.activity.BaseLifeActivity.onResume(Unknown Source:0)
	at com.netease.gl.ui.base.GLActivity.onResume(Unknown Source:0)
	at com.netease.gl.ui.activity.WelcomeActivity.onResume(Unknown Source:3)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1364)
	at android.app.Activity.performResume(Activity.java:7490)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4256)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4328)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
	at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(Unknown Source:23)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

@jtsky fixed的版本是多少呢？

**Comment by jtsky** [comment]
> 依赖为：'com.didichuxing.doraemonkit:doraemonkit:2.0.1'
> 机型：BLN-AL20
> 系统：Android 8.0
> 
> java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
> at android.view.ViewGroup.addView(ViewGroup.java:4799)
> at android.view.ViewGroup.addView(ViewGroup.java:4779)
> at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.attach(Unknown Source:207)
> at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.resumeAndAttachDokitViews(Unknown Source:320)
> at com.didichuxing.doraemonkit.ui.base.DokitViewManager.resumeAndAttachDokitViews(Unknown Source:2)
> at com.didichuxing.doraemonkit.DoraemonKit.resumeAndAttachDokitViews(Unknown Source:4)
> at com.didichuxing.doraemonkit.DoraemonKit.access$300(Unknown Source:0)
> at com.didichuxing.doraemonkit.DoraemonKit$2.onActivityResumed(Unknown Source:26)
> at android.app.Application.dispatchActivityResumed(Application.java:227)
> at android.app.Activity.onResume(Activity.java:1415)
> at android.support.v4.app.FragmentActivity.onResume(Unknown Source:0)
> at im.yixin.gl.log.page.view.LogActivity.onResume(Unknown Source:0)
> at im.yixin.gl.log.page.view.LogSwipeBackActivity.onResume(Unknown Source:0)
> at com.netease.gl.ui.activity.BaseLifeActivity.onResume(Unknown Source:0)
> at com.netease.gl.ui.base.GLActivity.onResume(Unknown Source:0)
> at com.netease.gl.ui.activity.WelcomeActivity.onResume(Unknown Source:3)
> at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1364)
> at android.app.Activity.performResume(Activity.java:7490)
> at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4256)
> at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4328)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
> at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(Unknown Source:23)
> at android.os.Handler.dispatchMessage(Handler.java:104)
> at android.os.Looper.loop(Looper.java:166)
> at android.app.ActivityThread.main(ActivityThread.java:7529)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
> 
> @jtsky fixed的版本是多少呢？

最新的版本中已经修复
