### ISSUE TITLE
java.lang.ClassCastException: com.didichuxing.doraemonkit.ui.d.a cannot be cast to com.didichuxing.doraemonkit.kit.timecounter.a

### ISSUE THREAD

**Issue by Smart-shine** [didi/DoraemonKit#334]
Android 版本集成
compile 'com.didichuxing.doraemonkit:doraemonkit:2.0.0'

debug的apk是可以的
release的apk安装后就crash了

日志信息
java.lang.ClassCastException: com.didichuxing.doraemonkit.ui.d.a cannot be cast to com.didichuxing.doraemonkit.kit.timecounter.a
        at com.didichuxing.doraemonkit.kit.timecounter.a.a.h(ActivityCounter.java:128)
        at com.didichuxing.doraemonkit.kit.timecounter.a.a.g(ActivityCounter.java:112)
        at com.didichuxing.doraemonkit.kit.timecounter.a.a$1$1.run(ActivityCounter.java:89)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6401)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
使用的小米的手机Note 3

**Comment by Smart-shine** [comment]
开启了混淆，keep下解决了

**Comment by lylh** [comment]
这个因为是有反射么?要不让为啥要keep呢

**Comment by Smart-shine** [comment]
看日志信息是这个包的不同目录下有两个名字相同的类，混到以后根据名字去找就找不到了

**Comment by zhaoxiuyu** [comment]
混淆配置有吗
