### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by fanfanxiaozu** [didi/DoraemonKit#342]
com.amitshekhar.debug.DebugDBInitProvider: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.net.wifi.WifiInfo.getIpAddress()' on a null object reference
at android.app.ActivityThread.installProvider(ActivityThread.java:5841)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:5430)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5369)
at android.app.ActivityThread.-wrap2(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6104)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.net.wifi.WifiInfo.getIpAddress()' on a null object reference
at com.amitshekhar.utils.NetworkUtils.getAddressLog(NetworkUtils.java:38)
at com.amitshekhar.DebugDB.initialize(DebugDB.java:62)
at com.amitshekhar.debug.DebugDBInitProvider.onCreate(DebugDBInitProvider.java:44)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1786)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1761)
at com.amitshekhar.debug.DebugDBInitProvider.attachInfo(DebugDBInitProvider.java:83)
at android.app.ActivityThread.installProvider(ActivityThread.java:5838)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:5430) 
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5369) 
at android.app.ActivityThread.-wrap2(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6104) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by jtsky** [comment]
> NetworkUtils

这个错误是我们引入的第三方库com.amitshekhar.android:debug-db:1.0.6内部报的空指针，我去给他们提个issue，我想问下这个错误在你那边是必现的吗？

**Comment by fanfanxiaozu** [comment]
某些手机上面必现的

**Comment by jtsky** [comment]
> 某些手机上面必现的
