### ISSUE TITLE
 java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by jhwsx** [didi/DoraemonKit#363]
Please complete the following informations.
## Expected behavior and actual behavior.

No crash

## Steps to reproduce the problem.

App Initialization

## Android or iOS? OS version? Brand? 

Android 19  Vivo X5Max+

## More informations such as error messages and stack traces are welcomed.

```
 java.lang.ExceptionInInitializerError
        at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211)
        at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211)
        at com.didichuxing.doraemonkit.util.DoraemonStatisticsUtil.uploadUserInfo(DoraemonStatisticsUtil.java:51)
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:392)
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:127)
        at com.prdsff.veryclean.MainApplication.onCreate(MainApplication.java:43)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1009)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4611)
        at android.app.ActivityThread.access$1500(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5373)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
        at okhttp3.internal.platform.AndroidPlatform.<clinit>(AndroidPlatform.kt:232)
        at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211) 
        at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179) 
        at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211) 
        at com.didichuxing.doraemonkit.util.DoraemonStatisticsUtil.uploadUserInfo(DoraemonStatisticsUtil.java:51) 
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:392) 
        at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:127) 
        at com.prdsff.veryclean.MainApplication.onCreate(MainApplication.java:43) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1009) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4611) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:5373) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645) 
        at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> ## Expected behavior and actual behavior.
> No crash
> 
> ## Steps to reproduce the problem.
> App Initialization
> 
> ## Android or iOS? OS version? Brand?
> Android 19 Vivo X5Max+
> 
> ## More informations such as error messages and stack traces are welcomed.
> ```
>  java.lang.ExceptionInInitializerError
>         at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211)
>         at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179)
>         at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180)
>         at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
>         at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211)
>         at com.didichuxing.doraemonkit.util.DoraemonStatisticsUtil.uploadUserInfo(DoraemonStatisticsUtil.java:51)
>         at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:392)
>         at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:127)
>         at com.prdsff.veryclean.MainApplication.onCreate(MainApplication.java:43)
>         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1009)
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4611)
>         at android.app.ActivityThread.access$1500(ActivityThread.java:153)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
>         at android.os.Handler.dispatchMessage(Handler.java:110)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.app.ActivityThread.main(ActivityThread.java:5373)
>         at java.lang.reflect.Method.invokeNative(Native Method)
>         at java.lang.reflect.Method.invoke(Method.java:515)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
>         at dalvik.system.NativeStart.main(Native Method)
>      Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
>         at okhttp3.internal.platform.AndroidPlatform.<clinit>(AndroidPlatform.kt:232)
>         at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211) 
>         at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179) 
>         at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180) 
>         at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219) 
>         at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211) 
>         at com.didichuxing.doraemonkit.util.DoraemonStatisticsUtil.uploadUserInfo(DoraemonStatisticsUtil.java:51) 
>         at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:392) 
>         at com.didichuxing.doraemonkit.DoraemonKit.install(DoraemonKit.java:127) 
>         at com.prdsff.veryclean.MainApplication.onCreate(MainApplication.java:43) 
>         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1009) 
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4611) 
>         at android.app.ActivityThread.access$1500(ActivityThread.java:153) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
>         at android.os.Handler.dispatchMessage(Handler.java:110) 
>         at android.os.Looper.loop(Looper.java:193) 
>         at android.app.ActivityThread.main(ActivityThread.java:5373) 
>         at java.lang.reflect.Method.invokeNative(Native Method) 
>         at java.lang.reflect.Method.invoke(Method.java:515) 
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645) 
>         at dalvik.system.NativeStart.main(Native Method) 
> ```

“ 欢迎更新到3.0beta1版本 ，应该已经解决，接入手册详见 http://www.dokit.cn/ 使用中心“
