### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amitshekhar/R$string;

### ISSUE THREAD

**Issue by cybkw** [didi/DoraemonKit#364]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amitshekhar/R$string;
        at com.amitshekhar.DebugDB.a(DebugDB.java:53)
        at com.amitshekhar.debug.encrypt.DebugDBEncryptInitProvider.onCreate(DebugDBEncryptInitProvider.java:21)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
        at com.amitshekhar.debug.encrypt.DebugDBEncryptInitProvider.attachInfo(DebugDBEncryptInitProvider.java:60)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6949)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6496)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6400)
        at android.app.ActivityThread.access$1300(ActivityThread.java:248)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1830)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7285)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amitshekhar.R$string" on path: DexPathList[[zip file "/data/app/com.scex.wine-vFnBOrycHbJBqlba5QoMWg==/base.apk"],nativeLibraryDirectories=[/data/app/com.scex.wine-vFnBOrycHbJBqlba5QoMWg==/lib/arm64, /data/app/com.scex.wine-vFnBOrycHbJBqlba5QoMWg==/base.apk!/lib/arm64-v8a, /system/lib64]]

**Comment by cybkw** [comment]
已解决，是分包的问题。   加入multidex
