### ISSUE TITLE
npe造成 AppCrash

### ISSUE THREAD

**Issue by lks6123** [didi/DoraemonKit#373]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
```
2019-12-26 17:43:49.619 27695-27901/com.tct.globalnet E/AndroidRuntime: FATAL EXCEPTION: pool-14-thread-1
    Process: com.tct.globalnet, PID: 27695
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$2.compare(ObsoleteUrlFactory.java:104)
        at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$2.compare(ObsoleteUrlFactory.java:101)
        at java.util.TreeMap.put(TreeMap.java:553)
        at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory.toMultimap(ObsoleteUrlFactory.java:283)
        at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$OkHttpURLConnection.getHeaderFields(ObsoleteUrlFactory.java:431)
        at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$DelegatingHttpsURLConnection.getHeaderFields(ObsoleteUrlFactory.java:1100)
     
```

**Comment by lks6123** [comment]
android 平台。 
DoraemonKit版本： 2.2.1

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。（如有）
> > 问题重现的步骤。（如有）
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 
> ```
> 2019-12-26 17:43:49.619 27695-27901/com.tct.globalnet E/AndroidRuntime: FATAL EXCEPTION: pool-14-thread-1
>     Process: com.tct.globalnet, PID: 27695
>     java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
>         at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$2.compare(ObsoleteUrlFactory.java:104)
>         at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$2.compare(ObsoleteUrlFactory.java:101)
>         at java.util.TreeMap.put(TreeMap.java:553)
>         at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory.toMultimap(ObsoleteUrlFactory.java:283)
>         at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$OkHttpURLConnection.getHeaderFields(ObsoleteUrlFactory.java:431)
>         at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$DelegatingHttpsURLConnection.getHeaderFields(ObsoleteUrlFactory.java:1100)
>      
> ```

已进行判空处理
