### ISSUE TITLE
从老版本1.x升级到3.0.0，不显示入口icon

### ISSUE THREAD

**Issue by lijianqiang12** [didi/DoraemonKit#420]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
四个手机，android、，miui，oppo，vivo均不显示
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 最好给我们提供可以复现问题的Demo
初始化：MyApp中调用： DoraemonKit.install(this@MyApp, null, "e63e1e5c9ed1c0f85a25281c81d9468e")

**Comment by jtsky** [comment]
请问控制台有其他报错信息吗？或者在你的主MainActivity的onCreate中手动调用DoraemonKit.show()。如果还是不行的话 可以在QQ群里@一下我 我叫金台

**Comment by lijianqiang12** [comment]
在mainactivity中调用show也不行，但是控制台有一些警告
2020-04-03 20:17:27.328 22659-22659/com.lijianqiang12.silent W/System.err: java.lang.NoSuchFieldException: No field mActivityList in class Landroid/app/ActivityThread; (declaration of 'android.app.ActivityThread' appears in /system/framework/framework.jar)
2020-04-03 20:17:27.328 22659-22659/com.lijianqiang12.silent W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
2020-04-03 20:17:27.328 22659-22659/com.lijianqiang12.silent W/System.err:     at com.blankj.utilcode.util.Utils$ActivityLifecycleImpl.getTopActivityByReflect(Utils.java:488)
2020-04-03 20:17:27.328 22659-22659/com.lijianqiang12.silent W/System.err:     at com.blankj.utilcode.util.Utils$ActivityLifecycleImpl.getTopActivity(Utils.java:386)
2020-04-03 20:17:27.328 22659-22659/com.lijianqiang12.silent W/System.err:     at com.blankj.utilcode.util.ActivityUtils.getTopActivity(ActivityUtils.java:1448)
2020-04-03 20:17:27.328 22659-22659/com.lijianqiang12.silent W/System.err:     at com.didichuxing.doraemonkit.kit.timecounter.counter.ActivityCounter.pause(ActivityCounter.java:48)
2020-04-03 20:17:27.328 22659-22659/com.lijianqiang12.silent W/System.err:     at com.didichuxing.doraemonkit.kit.timecounter.TimeCounterManager.onActivityPause(TimeCounterManager.java:91)
2020-04-03 20:17:27.329 22659-22659/com.lijianqiang12.silent W/System.err:     at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handlerActivity(ProxyHandlerCallback.java:76)
2020-04-03 20:17:27.329 22659-22659/com.lijianqiang12.silent W/System.err:     at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.preDispatch(ProxyHandlerCallback.java:59)
2020-04-03 20:17:27.329 22659-22659/com.lijianqiang12.silent W/System.err:     at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:39)
2020-04-03 20:17:27.329 22659-22659/com.lijianqiang12.silent W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:103)
2020-04-03 20:17:27.329 22659-22659/com.lijianqiang12.silent W/System.err:     at android.os.Looper.loop(Looper.java:213)
2020-04-03 20:17:27.329 22659-22659/com.lijianqiang12.silent W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8169)
2020-04-03 20:17:27.329 22659-22659/com.lijianqiang12.silent W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-04-03 20:17:27.329 22659-22659/com.lijianqiang12.silent W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
2020-04-03 20:17:27.329 22659-22659/com.lijianqiang12.silent W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
2020-04-03 20:17:27.335 22659-22806/com.lijianqiang12.silent I/TDLog:  setReportUncaughtExceptions: true
2020-04-03 20:17:27.344 22659-22659/com.lijianqiang12.silent W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@c53938f
2020-04-03 20:17:27.350 22659-22798/com.lijianqiang12.silent E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@b4b7ffa

**Comment by jtsky** [comment]
请升级到最新版本看下

**Comment by lijianqiang12** [comment]
ok了
