### ISSUE TITLE
项目报错

### ISSUE THREAD

**Issue by KM-BUG** [didi/DoraemonKit#434]
![image](https://user-images.githubusercontent.com/13640766/78655270-5adee100-78f8-11ea-8a54-14c524c4424d.png)

**Comment by KM-BUG** [comment]
Caused by: java.lang.IllegalStateException:Binary XML file line #56: Unable to find LayoutManager android.support.v7.widget.@2131689911
        at android.support.v7.widget.RecyclerView.createLayoutManager(RecyclerView.java:810)
        at android.support.v7.widget.RecyclerView.<init>(RecyclerView.java:713)
        at android.support.v7.widget.RecyclerView.<init>(RecyclerView.java:647)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:651)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)

**Comment by jtsky** [comment]
> Caused by: java.lang.IllegalStateException:Binary XML file line #56: Unable to find LayoutManager android.support.v7.widget.@2131689911
> at android.support.v7.widget.RecyclerView.createLayoutManager(RecyclerView.java:810)
> at android.support.v7.widget.RecyclerView.(RecyclerView.java:713)
> at android.support.v7.widget.RecyclerView.(RecyclerView.java:647)
> at java.lang.reflect.Constructor.newInstance0(Native Method)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
> at android.view.LayoutInflater.createView(LayoutInflater.java:651)
> at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
> at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
> at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)

请问你的项目已经适配androidx了吗，如果已经适配可以接入v3.1.1版本,如果没有适配的话则需要接入v3.0.2版本

**Comment by KM-BUG** [comment]
没有适配androidX

**Comment by jtsky** [comment]
> 没有适配androidX

那你接入的是v3.0.2版本的吗？

**Comment by KM-BUG** [comment]
好的，我试一下，我看集成的还是挺老的版本：0.2.0

**Comment by KM-BUG** [comment]
好的，我试一下，感谢
