### ISSUE TITLE
接入后打开大图拦截 App闪退

### ISSUE THREAD

**Issue by JasonHezz** [didi/DoraemonKit#438]
接入后打开大图拦截 App闪退

崩溃日记
```
  java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:164)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:67)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:25)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by jtsky** [comment]
> 接入后打开大图拦截 App闪退
> 
> 崩溃日记
> 
> ```
>   java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
>         at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:164)
>         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:67)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:25)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:42)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
>         at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
>         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:764)
> ```

请确认下你的okhttp版本是多少？或者升级到最新的3.1.2版本试试

**Comment by jtsky** [comment]
> 接入后打开大图拦截 App闪退
> 
> 崩溃日记
> 
> ```
>   java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
>         at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:164)
>         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:67)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:25)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:42)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
>         at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
>         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:764)
> ```

dokitExt {
//整个dokit的插件开关
dokitPluginSwitch = true
//函数耗时的开关
slowMethodSwitch = true
//大图检测的开关
bigImgSwitch = true
//函数耗时的自定义阈值 单位为ms 1000ms = 1s
thresholdTime = 200
//在指定的包名业务代码下插入代码
packageNames = ["com.didichuxing.doraemondemo"]
}
可以通过以上配置进行字节码插装的开和关。
具体请参考:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
