### ISSUE TITLE
3.1.2 闪退

### ISSUE THREAD

**Issue by Aracoix** [didi/DoraemonKit#449]
闪退

Android 普通集成 第二次run 小米8SE

apply plugin: 'com.didi.dokit'

dokitExt {
    //整个dokit的插件开关
    dokitPluginSwitch = true
    //函数耗时的开关
    slowMethodSwitch = true
    //大图检测的开关
    bigImgSwitch = true
    //函数耗时的自定义阈值 单位为ms 1000ms = 1s
    thresholdTime = 200
    //在指定的包名业务代码下插入代码
    packageNames = ["com.ihomefnt"]
}

 dependencies {
.....
debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:3.1.2'
        releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:3.1.2'
        debugImplementation 'com.didichuxing.doraemonkit:doraemonkit-leakcanary:3.1.2'
}

init 

class MainApplication : MultiDexApplication() {

 override fun onCreate() {
        super.onCreate()
 if (inMainProcess()) {
 DoraemonKit.install(this, null,"XXXX");
}
}

 java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:164)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:67)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:25)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:47)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:25)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by jtsky** [comment]
> 闪退
> 
> Android 普通集成 第二次run 小米8SE
> 
> apply plugin: 'com.didi.dokit'
> 
> dokitExt {
> //整个dokit的插件开关
> dokitPluginSwitch = true
> //函数耗时的开关
> slowMethodSwitch = true
> //大图检测的开关
> bigImgSwitch = true
> //函数耗时的自定义阈值 单位为ms 1000ms = 1s
> thresholdTime = 200
> //在指定的包名业务代码下插入代码
> packageNames = ["com.ihomefnt"]
> }
> 
> dependencies {
> .....
> debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:3.1.2'
> releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:3.1.2'
> debugImplementation 'com.didichuxing.doraemonkit:doraemonkit-leakcanary:3.1.2'
> }
> 
> init
> 
> class MainApplication : MultiDexApplication() {
> 
> override fun onCreate() {
> super.onCreate()
> if (inMainProcess()) {
> DoraemonKit.install(this, null,"8cec365376deb7139e125fb2066ab92d");
> }
> }
> 
> java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
> at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:164)
> at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:67)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:25)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:42)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:47)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:25)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:42)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
> at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
> at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:919)

你的 okhttp 版本是不是3.14.+？如果是的话 当前的解决方案是把okhttp版本降到3.12.1。这个问题我会在下个礼拜发布新本修复

**Comment by Aracoix** [comment]
好的，谢谢

**Comment by Aracoix** [comment]
3.12.1 依旧闪退，同样的问题

**Comment by Aracoix** [comment]
> 3.12.1 依旧闪退，同样的问题

我自己的问题，有 其他包引了3.14+
顺便贴一下我的解决办法
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
    configurations.all {
        resolutionStrategy {
            eachDependency { DependencyResolveDetails details ->
                if (details.requested.group == 'com.squareup.okhttp3') {
                    details.useVersion "3.12.1"
                }
            }
        }
    }
}

**Comment by jtsky** [comment]
> > 3.12.1 依旧闪退，同样的问题
> 
> 我自己的问题，有 其他包引了3.14+
> 顺便贴一下我的解决办法
> allprojects {
> repositories {
> google()
> jcenter()
> maven { url "https://jitpack.io" }
> }
> configurations.all {
> resolutionStrategy {
> eachDependency { DependencyResolveDetails details ->
> if (details.requested.group == 'com.squareup.okhttp3') {
> details.useVersion "3.12.1"
> }
> }
> }
> }
> }

ok 也可以关注下我们的官网dokit.cn
以及使用中心:http://xingyun.xiaojukeji.com/docs/dokit/#/intro
