### ISSUE TITLE
DoraemonInterceptor 拦截器报错

### ISSUE THREAD

**Issue by winchances** [didi/DoraemonKit#458]
java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:164)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:81)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:29)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:49)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by jtsky** [comment]
> java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
> at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:164)
> at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:81)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:29)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:49)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
> at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
> at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:764)

请确认你的项目是否已经升级到androidx并升级到最新的dokit版本
参考:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide

**Comment by winchances** [comment]
项目运行环境是 androidx + doraemonkit V3.1.4，

**Comment by jtsky** [comment]
> 项目运行环境是 androidx + doraemonkit V3.1.4，

好的 我这边看下

**Comment by jtsky** [comment]
> 项目运行环境是 androidx + doraemonkit V3.1.4，

是在使用大图检测时出现的错误吗？

**Comment by winchances** [comment]
不开启大图检测也会出现

**Comment by winchances** [comment]
> > 项目运行环境是 androidx + doraemonkit V3.1.4，
> 
> 是在使用大图检测时出现的错误吗？

不开启大图检测也会出现

**Comment by jtsky** [comment]
> > > 项目运行环境是 androidx + doraemonkit V3.1.4，
> > 
> > 
> > 是在使用大图检测时出现的错误吗？
> 
> 不开启大图检测也会出现
![image](https://user-images.githubusercontent.com/4486497/80299787-adaa0b00-87c9-11ea-9c6c-c0fccc575087.png)


你的okhttp 版本是3.14+吗 感觉好像是okhttp 库的问题 我这边再调用前其实已经response.close()了

**Comment by winchances** [comment]
> > > > 项目运行环境是 androidx + doraemonkit V3.1.4，
> > > 
> > > 
> > > 是在使用大图检测时出现的错误吗？
> > 
> > 
> > 不开启大图检测也会出现
> > ![image](https://user-images.githubusercontent.com/4486497/80299787-adaa0b00-87c9-11ea-9c6c-c0fccc575087.png)
> 
> 你的okhttp 版本是3.14+吗 感觉好像是okhttp 库的问题 我这边再调用前其实已经response.close()了


okhttp 版本是3.14.7

**Comment by jtsky** [comment]
> > > > > 项目运行环境是 androidx + doraemonkit V3.1.4，
> > > > 
> > > > 
> > > > 是在使用大图检测时出现的错误吗？
> > > 
> > > 
> > > 不开启大图检测也会出现
> > > ![image](https://user-images.githubusercontent.com/4486497/80299787-adaa0b00-87c9-11ea-9c6c-c0fccc575087.png)
> > 
> > 
> > 你的okhttp 版本是3.14+吗 感觉好像是okhttp 库的问题 我这边再调用前其实已经response.close()了
> 
> okhttp 版本是3.14.7

dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
注意:
插件配置模块的配置和以前有所区别，请重点关注下。

假如新的版本已经解决你的问题，可以选择自己关闭此issues或者回复此条信息由我来关闭。
