### ISSUE TITLE
接入后应用的网络不可用

### ISSUE THREAD

**Issue by xie123** [didi/DoraemonKit#471]
> 期望的表现和实际的表现。（如有）
期望的表现：网络可以用
实际的表现：任何网络请求都是 ConnectException
> 问题重现的步骤。（如有）
android studion run 之后就是这样
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
android 设备，系统是android7.1 .tv 盒子

**Comment by xie123** [comment]
java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
    at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:54)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:30)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:49)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)

**Comment by jtsky** [comment]
> java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:54)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:30)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:49)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
> at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
> at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
> at java.lang.Thread.run(Thread.java:761)

dokit版本是多少?

**Comment by xie123** [comment]
应该是引入了多个okhttp 或者io 的版本
