### ISSUE TITLE
okhttp3.ResponseBody okhttp3.Response.body()' on a null object reference

### ISSUE THREAD

**Issue by zzzsssbo** [didi/DoraemonKit#476]
请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（偶尔出现，暂时没发现必现的操作流程）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（Android 系统版本android10，小米）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 最好给我们提供可以复现问题的Demo
`E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.gongxuanwang.linxuan, PID: 12629
    java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.ResponseBody okhttp3.Response.body()' on a null object reference
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:54)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:30)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:49)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by jtsky** [comment]
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。（如有）
> > 问题重现的步骤。（偶尔出现，暂时没发现必现的操作流程）
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（Android 系统版本android10，小米）
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> > 最好给我们提供可以复现问题的Demo
> > `E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher     Process: com.gongxuanwang.linxuan, PID: 12629     java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.ResponseBody okhttp3.Response.body()' on a null object reference         at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:54)         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)         at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:30)         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)         at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:49)         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)         at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)         at java.lang.Thread.run(Thread.java:919)`

下个版本修复

**Comment by zzzsssbo** [comment]
嗯嗯
