### ISSUE TITLE
网络 Crash

### ISSUE THREAD

**Issue by changjiashuai** [didi/DoraemonKit#506]
java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.ResponseBody okhttp3.Response.body()' on a null object reference
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:54)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:30)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:49)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（点击网络--》操作应用）
> Android 系统版本是Android 10 手机品牌是一加7 Pro
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 最好给我们提供可以复现问题的Demo

**Comment by jtsky** [comment]
> java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.ResponseBody okhttp3.Response.body()' on a null object reference
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor.intercept(DoraemonInterceptor.java:54)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor.intercept(LargePictureInterceptor.java:30)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:49)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
> at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
> at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:919)
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。（如有）
> > 问题重现的步骤。（点击网络--》操作应用）
> > Android 系统版本是Android 10 手机品牌是一加7 Pro
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> > 最好给我们提供可以复现问题的Demo

dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
注意:
插件配置模块的配置和以前有所区别，请重点关注下。

假如新的版本已经解决你的问题，可以选择自己关闭此issues或者回复此条信息由我来关闭。
