### ISSUE TITLE
Android频繁崩溃问题

### ISSUE THREAD

**Issue by wander95969** [didi/DoraemonKit#508]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 问题重现的步骤。（多点几次常用工具里的选项，就会崩溃）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（Android10，targetSdk版本29，华为P30手机，OkHttp版本为4.3.0，retrofit版本为2.7.1，不想将OkHttp版本）

java.lang.ExceptionInInitializerError
        at com.didichuxing.doraemonkit.okgo.DokitOkGo.getInstance(DokitOkGo.java:92)
        at com.didichuxing.doraemonkit.okgo.request.base.Request.<init>(Request.java:77)
        at com.didichuxing.doraemonkit.okgo.request.base.BodyRequest.<init>(BodyRequest.java:59)
        at com.didichuxing.doraemonkit.okgo.request.PostRequest.<init>(PostRequest.java:36)
        at com.didichuxing.doraemonkit.okgo.DokitOkGo.post(DokitOkGo.java:110)
        at com.didichuxing.doraemonkit.datapick.DataPickManager.realPost(DataPickManager.java:108)
        at com.didichuxing.doraemonkit.datapick.DataPickManager.postData(DataPickManager.java:97)
        at com.didichuxing.doraemonkit.datapick.DataPickManager.addData(DataPickManager.java:66)
        at com.didichuxing.doraemonkit.kit.main.MainIconDokitView$1.onClick(MainIconDokitView.java:39)
        at android.view.View.performClick(View.java:7189)
        at com.didichuxing.doraemonkit.kit.core.TouchProxy.onTouchEvent(TouchProxy.java:74)
        at com.didichuxing.doraemonkit.kit.core.AbsDokitView$3.onTouch(AbsDokitView.java:182)
        at android.view.View.dispatchTouchEvent(View.java:13496)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3067)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2752)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3073)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3073)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:613)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1933)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4127)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:559)
        at android.view.View.dispatchPointerEvent(View.java:13763)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5819)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5614)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5058)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5111)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5077)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5234)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5085)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5291)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5058)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5111)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5077)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5085)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5058)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7949)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7900)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7854)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8139)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:233)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:363)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.IllegalArgumentException: Required method checkServerTrusted(X509Certificate[], String, String, String) missing
    	at android.net.http.X509TrustManagerExtensions.<init>(X509TrustManagerExtensions

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 问题重现的步骤。（多点几次常用工具里的选项，就会崩溃）
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（Android10，targetSdk版本29，华为P30手机，OkHttp版本为4.3.0，retrofit版本为2.7.1，不想将OkHttp版本）
> 
> java.lang.ExceptionInInitializerError
> at com.didichuxing.doraemonkit.okgo.DokitOkGo.getInstance(DokitOkGo.java:92)
> at com.didichuxing.doraemonkit.okgo.request.base.Request.(Request.java:77)
> at com.didichuxing.doraemonkit.okgo.request.base.BodyRequest.(BodyRequest.java:59)
> at com.didichuxing.doraemonkit.okgo.request.PostRequest.(PostRequest.java:36)
> at com.didichuxing.doraemonkit.okgo.DokitOkGo.post(DokitOkGo.java:110)
> at com.didichuxing.doraemonkit.datapick.DataPickManager.realPost(DataPickManager.java:108)
> at com.didichuxing.doraemonkit.datapick.DataPickManager.postData(DataPickManager.java:97)
> at com.didichuxing.doraemonkit.datapick.DataPickManager.addData(DataPickManager.java:66)
> at com.didichuxing.doraemonkit.kit.main.MainIconDokitView$1.onClick(MainIconDokitView.java:39)
> at android.view.View.performClick(View.java:7189)
> at com.didichuxing.doraemonkit.kit.core.TouchProxy.onTouchEvent(TouchProxy.java:74)
> at com.didichuxing.doraemonkit.kit.core.AbsDokitView$3.onTouch(AbsDokitView.java:182)
> at android.view.View.dispatchTouchEvent(View.java:13496)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3067)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2752)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3073)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3073)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
> at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:613)
> at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1933)
> at android.app.Activity.dispatchTouchEvent(Activity.java:4127)
> at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
> at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:559)
> at android.view.View.dispatchPointerEvent(View.java:13763)
> at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5819)
> at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5614)
> at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5058)
> at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5111)
> at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5077)
> at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5234)
> at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5085)
> at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5291)
> at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5058)
> at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5111)
> at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5077)
> at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5085)
> at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5058)
> at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7949)
> at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7900)
> at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7854)
> at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8139)
> at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:233)
> at android.os.MessageQueue.nativePollOnce(Native Method)
> at android.os.MessageQueue.next(MessageQueue.java:363)
> at android.os.Looper.loop(Looper.java:173)
> at android.app.ActivityThread.main(ActivityThread.java:8147)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
> Caused by: java.lang.IllegalArgumentException: Required method checkServerTrusted(X509Certificate[], String, String, String) missing
> at android.net.http.X509TrustManagerExtensions.(X509TrustManagerExtensions

暂时还没针对高版本的okhttp进行适配
