### ISSUE TITLE
DoraemonKit 在android10 上的 OKhttp bug

### ISSUE THREAD

**Issue by tracyly** [didi/DoraemonKit#566]
java.lang.IllegalStateException: Unable to extract the trust manager on Android10Platform, sslSocketFactory is class com.android.org.conscrypt.OpenSSLSocketFactoryImpl
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:751)
        at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$OkHttpsURLConnection.setSSLSocketFactory(ObsoleteUrlFactory.java:1300)
        at com.tencent.imsdk.looper.HttpClient$3.run(HttpClient.java:135)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
    	at java.util.concurre

**Comment by jtsky** [comment]
> java.lang.IllegalStateException: Unable to extract the trust manager on Android10Platform, sslSocketFactory is class com.android.org.conscrypt.OpenSSLSocketFactoryImpl
> at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:751)
> at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$OkHttpsURLConnection.setSSLSocketFactory(ObsoleteUrlFactory.java:1300)
> at com.tencent.imsdk.looper.HttpClient$3.run(HttpClient.java:135)
> at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
> at java.util.concurre

我一直都是用Android 10进行测试的  没问题  你的okhttp版本是多少？

**Comment by tracyly** [comment]
okhttp 3.12.1

**Comment by tracyly** [comment]
> > java.lang.IllegalStateException: Unable to extract the trust manager on Android10Platform, sslSocketFactory is class com.android.org.conscrypt.OpenSSLSocketFactoryImpl
> > at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:751)
> > at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$OkHttpsURLConnection.setSSLSocketFactory(ObsoleteUrlFactory.java:1300)
> > at com.tencent.imsdk.looper.HttpClient$3.run(HttpClient.java:135)
> > at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
> > at java.util.concurre
> 
> 我一直都是用Android 10进行测试的 没问题 你的okhttp版本是多少？

okhttp 3.12.1

**Comment by SkywalkerDarren** [comment]
java.lang.IllegalStateException: Unable to extract the trust manager on Android10Platform, sslSocketFactory is class com.android.org.conscrypt.OpenSSLSocketFactoryImpl
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:751)
        at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$OkHttpsURLConnection.setSSLSocketFactory(ObsoleteUrlFactory.java:1305)
        at com.arialyy.aria.http.ConnectionHelp.handleConnection(ConnectionHelp.java:120)
        at com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:81)
        at com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:101)
        at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
        at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
        at java.lang.Thread.run(Thread.java:923)

```kotlin
 /**
     * Sets the socket factory used to secure HTTPS connections. If unset, the system default will
     * be used.
     *
     * @deprecated [SSLSocketFactory] does not expose its [X509TrustManager], which is a field that
     *     OkHttp needs to build a clean certificate chain. This method instead must use reflection
     *     to extract the trust manager. Applications should prefer to call
     *     `sslSocketFactory(SSLSocketFactory, X509TrustManager)`, which avoids such reflection.
     */
    @Deprecated(
        message = "Use the sslSocketFactory overload that accepts a X509TrustManager.",
        level = DeprecationLevel.ERROR
    )
    fun sslSocketFactory(sslSocketFactory: SSLSocketFactory) = apply {
      if (sslSocketFactory != this.sslSocketFactoryOrNull) {
        this.routeDatabase = null
      }

      this.sslSocketFactoryOrNull = sslSocketFactory
      this.x509TrustManagerOrNull = Platform.get().trustManager(sslSocketFactory) ?: throw IllegalStateException(
          "Unable to extract the trust manager on ${Platform.get()}, " +
              "sslSocketFactory is ${sslSocketFactory.javaClass}")
      this.certificateChainCleaner = Platform.get().buildCertificateChainCleaner(x509TrustManagerOrNull!!)
    }
```

同样的问题
okhttp3 4.8.1
dokitx 3.3.5

**Comment by gudujiucheng** [comment]
同样此问题+1
okhttp:3.11.0
dokitx 3.3.5

**Comment by Petterpx** [comment]
同样的问题
okhttp 4.7.2
dokitx 3.3.5

**Comment by AllenWen** [comment]
同样的问题
okhttp 4.8.1
dokitx 3.3.5

**Comment by AllenWen** [comment]
> 同样的问题
> okhttp 4.8.1
> dokitx 3.3.5

复写了OkHttpsURLConnection的setSSLSocketFactory方法，然后用classplugin替换了class，就OK了
`@Override
        public void setSSLSocketFactory(SSLSocketFactory sslSocketFactory) {
            if (sslSocketFactory == null) {
                throw new IllegalArgumentException("sslSocketFactory == null");
            }
            // This fails in JDK 9 because OkHttp is unable to extract the trust manager.
            try {
                Log.d("kucoinReplace", "start");
                TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
                trustManagerFactory.init((KeyStore) null);
                TrustManager[] trustManagers = trustManagerFactory.getTrustManagers();
                if (trustManagers.length != 1 || !(trustManagers[0] instanceof X509TrustManager)) {
                    Log.d("kucoinReplace", "trust manager error");
                    throw new IllegalStateException("Unexpected default trust managers:"
                            + Arrays.toString(trustManagers));
                }
                X509TrustManager trustManager = (X509TrustManager) trustManagers[0];
                delegate.client = delegate.client.newBuilder()
                        .sslSocketFactory(sslSocketFactory, trustManager).build();
            } catch (Exception e) {
                Log.e("kucoinReplace", "exception" + e.toString());
                e.printStackTrace();
            }
        }`

**Comment by knyou** [comment]
同样遇到+ 1

**Comment by wwwtete** [comment]
+1

**Comment by lixbandroid** [comment]
同样的问题+1 
好像是因为下载https 文件，由于没有设置ca证书，而使用了绕过证书的方式，导致了这个问题

**Comment by Yalun-Yong** [comment]
最后怎么解决的呀？我也遇到这个问题了？

**Comment by mengxn** [comment]
`com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$OkHttpsURLConnection.setSSLSocketFactory`调用了过时的方法，需要进行替换，参考`https://github.com/square/okhttp/issues/5878`

**Comment by trenail** [comment]
同样的问题
okhttp 4.9.3
dokitx 3.5.0.1
