### ISSUE TITLE
Fragment 切换崩溃

### ISSUE THREAD

**Issue by TheGrandDuelist** [didi/DoraemonKit#570]
>Dokit 3.1.8版本，debug版本集成后切换底部导航栏，fragment用replace方式
> Android 9， Huawei STF-AL00
> java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.fragment.app.FragmentManagerImpl.isDestroyed()' on a null object reference
        at androidx.fragment.app.Fragment.performDetach(Fragment.java:2849)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1034)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1310)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2825)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:434)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
> 最好给我们提供可以复现问题的Demo

**Comment by jtsky** [comment]
> > Dokit 3.1.8版本，debug版本集成后切换底部导航栏，fragment用replace方式
> > Android 9， Huawei STF-AL00
> > java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.fragment.app.FragmentManagerImpl.isDestroyed()' on a null object reference
> > at androidx.fragment.app.Fragment.performDetach(Fragment.java:2849)
> > at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1034)
> > at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
> > at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1310)
> > at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
> > at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
> > at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2825)
> > at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
> > at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
> > at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:434)
> > at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
> > at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
> > at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
> > at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
> > at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
> > at android.os.Handler.handleCallback(Handler.java:907)
> > at android.os.Handler.dispatchMessage(Handler.java:105)
> > at android.os.Looper.loop(Looper.java:216)
> > at android.app.ActivityThread.main(ActivityThread.java:7625)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

看这异常信息好像不是dokit导致的，并没有定位到具体的dokit代码

**Comment by TheGrandDuelist** [comment]
> 看这异常信息好像不是dokit导致的，并没有定位到具体的dokit代码

app只要引入了dokit就会崩溃，radioGroup+fragment切换app tab页面，报这个异常。app是已经上线的稳定版本，应该不是我这里的问题，

**Comment by jtsky** [comment]
> > 看这异常信息好像不是dokit导致的，并没有定位到具体的dokit代码
> 
> app只要引入了dokit就会崩溃，radioGroup+fragment切换app tab页面，报这个异常。app是已经上线迭代了的稳定版本，猜测dokit适配这里是不是有什么问题，或者能提供一些思路，供参考调试呢？

断点打在DokitFragmentLifecycleCallbacks的回调函数里  看看是不是这里抛出的异常
