### ISSUE TITLE
一直在循环调用, 一直到OOM, 卡死了

### ISSUE THREAD

**Issue by demoface** [didi/DoraemonKit#671]
使用的手机是小米Note8   android10
doraemonkit版本 3.1.5

2020-10-14 15:27:13.494 25740-25740/? W/System.err:     at $Proxy4.getDeviceId(Unknown Source)
2020-10-14 15:27:13.494 25740-25740/? W/System.err: 	... 2077 more
2020-10-14 15:27:13.497 25740-25740/? W/System.err: Caused by: java.lang.reflect.InvocationTargetException
2020-10-14 15:27:13.497 25740-25740/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-10-14 15:27:13.497 25740-25740/? W/System.err:     at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
2020-10-14 15:27:13.497 25740-25740/? W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
2020-10-14 15:27:13.497 25740-25740/? W/System.err: 	... 2078 more
2020-10-14 15:27:13.499 25740-25740/? W/System.err: Caused by: java.lang.reflect.UndeclaredThrowableException
2020-10-14 15:27:13.499 25740-25740/? W/System.err:     at $Proxy4.getDeviceId(Unknown Source)
2020-10-14 15:27:13.499 25740-25740/? W/System.err: 	... 2081 more
2020-10-14 15:27:13.502 25740-25740/? W/System.err: Caused by: java.lang.reflect.InvocationTargetException
2020-10-14 15:27:13.502 25740-25740/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-10-14 15:27:13.502 25740-25740/? W/System.err:     at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
2020-10-14 15:27:13.502 25740-25740/? W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
2020-10-14 15:27:13.502 25740-25740/? W/System.err: 	... 2082 more
2020-10-14 15:27:13.505 25740-25740/? W/System.err: Caused by: java.lang.reflect.UndeclaredThrowableException
2020-10-14 15:27:13.505 25740-25740/? W/System.err:     at $Proxy4.getDeviceId(Unknown Source)
2020-10-14 15:27:13.505 25740-25740/? W/System.err: 	... 2085 more
2020-10-14 15:27:13.508 25740-25740/? W/System.err: Caused by: java.lang.reflect.InvocationTargetException
2020-10-14 15:27:13.508 25740-25740/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-10-14 15:27:13.508 25740-25740/? W/System.err:     at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
2020-10-14 15:27:13.508 25740-25740/? W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
2020-10-14 15:27:13.508 25740-25740/? W/System.err: 	... 2086 more
2020-10-14 15:27:13.511 25740-25740/? W/System.err: Caused by: java.lang.reflect.UndeclaredThrowableException
2020-10-14 15:27:13.511 25740-25740/? W/System.err:     at $Proxy4.getDeviceId(Unknown Source)
2020-10-14 15:27:13.511 25740-25740/? W/System.err: 	... 2089 more
2020-10-14 15:27:13.514 25740-25740/? W/System.err: Caused by: java.lang.reflect.InvocationTargetException
2020-10-14 15:27:13.514 25740-25740/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-10-14 15:27:13.514 25740-25740/? W/System.err:     at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
2020-10-14 15:27:13.514 25740-25740/? W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
2020-10-14 15:27:13.514 25740-25740/? W/System.err: 	... 2090 more
2020-10-14 15:27:13.517 25740-25740/? W/System.err: Caused by: java.lang.reflect.UndeclaredThrowableException
2020-10-14 15:27:13.517 25740-25740/? W/System.err:     at $Proxy4.getDeviceId(Unknown Source)
2020-10-14 15:27:13.517 25740-25740/? W/System.err: 	... 2093 more
2020-10-14 15:27:13.519 25740-25740/? W/System.err: Caused by: java.lang.reflect.InvocationTargetException
2020-10-14 15:27:13.520 25740-25740/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-10-14 15:27:13.520 25740-25740/? W/System.err:     at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
2020-10-14 15:27:13.520 25740-25740/? W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
2020-10-14 15:27:13.520 25740-25740/? W/System.err: 	... 2094 more
2020-10-14 15:27:13.522 25740-25740/? W/System.err: Caused by: java.lang.reflect.UndeclaredThrowableException
2020-10-14 15:27:13.522 25740-25740/? W/System.err:     at $Proxy4.getDeviceId(Unknown Source)
2020-10-14 15:27:13.522 25740-25740/? W/System.err: 	... 2097 more
2020-10-14 15:27:13.525 25740-25740/? W/System.err: Caused by: java.lang.reflect.InvocationTargetException
2020-10-14 15:27:13.525 25740-25740/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-10-14 15:27:13.525 25740-25740/? W/System.err:     at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
2020-10-14 15:27:13.525 25740-25740/? W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
2020-10-14 15:27:13.525 25740-25740/? W/System.err: 	... 2098 more
2020-10-14 15:27:13.528 25740-25740/? W/System.err: Caused by: java.lang.reflect.UndeclaredThrowableException
2020-10-14 15:27:13.528 25740-25740/? W/System.err:     at $Proxy4.getDeviceId(Unknown Source)
2020-10-14 15:27:13.528 25740-25740/? W/System.err: 	... 2101 more
2020-10-14 15:27:13.531 25740-25740/? W/System.err: Caused by: java.lang.reflect.InvocationTargetException
2020-10-14 15:27:13.531 25740-25740/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-10-14 15:27:13.531 25740-25740/? W/System.err:     at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)

**Comment by runningmoonlight** [comment]
我也遇到了这个问题，另外还有图片闪烁、有手机出现未知native崩溃的问题。
    …………
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.didichuxing.doraemonkit.kit.gpsmock.BaseServiceHooker.invoke(BaseServiceHooker.java:48)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy8.getNetworkTypeForSubscriber(Unknown Source)
    at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2651)
    at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2613)
    at android.app.Activity.performResume(Activity.java:8222)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4894)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4947)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
    at com.jingdong.aura.core.reflection.a$b.handleMessage(SourceFile:59)
    at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:40)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8349)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by RygelTang** [comment]
这个问题可以看看是不是重复初始化了
