### ISSUE TITLE
android 引入 classpath 'com.didichuxing.doraemonkit:dokit-plugin:3.3.5' 就出现Caused by: java.lang.NoSuchFieldError: ASCII

### ISSUE THREAD

**Issue by xiesiwen** [didi/DoraemonKit#712]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 最好给我们提供可以复现问题的Demo

**Comment by xiaohuzi0113** [comment]
我也遇到了这样的问题，接入dokit后，应用启动登录进入MainActivity后崩溃，在登录页无异常，报错信息如下
 java.lang.NoSuchFieldError: No field mActive of type Landroid/util/SparseArray; in class Landroidx/fragment/app/FragmentManagerImpl; or its superclasses (declaration of 'androidx.fragment.app.FragmentManagerImpl' appears in /data/app/xxx(包名）-VNNA7SnEdO4BlKRVDYSe6A==/base.apk)
        at androidx.fragment.app.FragmentationMagician.getActiveFragments(FragmentationMagician.java:153)
        at me.yokeyword.fragmentation.SupportHelper.getPreFragment(SupportHelper.java:95)
        at me.yokeyword.fragmentation.SupportFragmentDelegate$3.run(SupportFragmentDelegate.java:611)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by xiaohuzi0113** [comment]
排查出来，是因为项目集成了第三方fragment框架，改成me.yokeyword:fragmentationx:1.0.2就可以了，兼容androidx
