### ISSUE TITLE
【Flutter】-[DioErrorType.other]: type 'Null' is not a subtype of type 'FutureOr<_HttpClientRequest>'

### ISSUE THREAD

**Issue by SheepYang1993** [didi/DoraemonKit#820]
Android10
dokit: ^0.8.0-nullsafety.0
flutter2.0
```
I/flutter (27642): DioError [DioErrorType.other]: type 'Null' is not a subtype of type 'FutureOr<_HttpClientRequest>'
I/flutter (27642): #0      _FutureListener.handleError (dart:async/future_impl.dart:166:20)
I/flutter (27642): #1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:716:47)
I/flutter (27642): #2      Future._propagateToListeners (dart:async/future_impl.dart:737:24)
I/flutter (27642): #3      Future._completeError (dart:async/future_impl.dart:547:5)
I/flutter (27642): #4      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:603:7)
I/flutter (27642): #5      _rootRun (dart:async/zone.dart:1354:13)
I/flutter (27642): #6      _CustomZone.run (dart:async/zone.dart:1258:19)
I/flutter (27642): #7      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
I/flutter (27642): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
I/flutter (27642): #9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
I/flutter (27642): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by kkkman22** [comment]
me too!!!!

**Comment by rzrobert** [comment]
me too!
