### ISSUE TITLE
Android 8.0 使用位置模拟时会出现以下问题

### ISSUE THREAD

**Issue by RubinTry** [didi/DoraemonKit#821]
Caused by: java.lang.UnsupportedOperationException: For security reasons, WebView is not allowed in privileged processes
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:187)
	at android.webkit.WebView.getFactory(WebView.java:2341)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2336)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2395)
	at android.view.View.<init>(View.java:4023)
	at android.view.View.<init>(View.java:4146)
	at android.view.ViewGroup.<init>(ViewGroup.java:579)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
	at android.webkit.WebView.<init>(WebView.java:627)
	at android.webkit.WebView.<init>(WebView.java:572)
	at android.webkit.WebView.<init>(WebView.java:555)
	at android.webkit.WebView.<init>(WebView.java:542)
	at com.didichuxing.doraemonkit.widget.webview.MyWebView.<init>(MyWebView.java:40)
	... 40 more

平台：Android
dokit版本：io.github.didi.dokit:dokitx:3.4.0-alpha02
no-op:：io.github.didi.dokit:dokitx-no-op:3.4.0-alpha02
classpath  ：'io.github.didi.dokit:dokitx-plugin:3.4.0-alpha02'

**Comment by RubinTry** [comment]
这是完整日志
```javascripe
java stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{cc.huasky.quyun.forbus/com.didichuxing.doraemonkit.kit.core.UniversalActivity}: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class com.didichuxing.doraemonkit.widget.webview.MyWebView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
	at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class com.didichuxing.doraemonkit.widget.webview.MyWebView
Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class com.didichuxing.doraemonkit.widget.webview.MyWebView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.view.LayoutInflater.inflate(<Xposed>)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at com.didichuxing.doraemonkit.kit.core.BaseFragment.onCreateView(BaseFragment.java:50)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2950)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:515)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3122)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3056)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:473)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6740)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2629)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
	at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.UnsupportedOperationException: For security reasons, WebView is not allowed in privileged processes
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:187)
	at android.webkit.WebView.getFactory(WebView.java:2341)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2336)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2395)
	at android.view.View.<init>(View.java:4023)
	at android.view.View.<init>(View.java:4146)
	at android.view.ViewGroup.<init>(ViewGroup.java:579)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
	at android.webkit.WebView.<init>(WebView.java:627)
	at android.webkit.WebView.<init>(WebView.java:572)
	at android.webkit.WebView.<init>(WebView.java:555)
	at android.webkit.WebView.<init>(WebView.java:542)
	at com.didichuxing.doraemonkit.widget.webview.MyWebView.<init>(MyWebView.java:40)
```

**Comment by RubinTry** [comment]
java stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{/com.didichuxing.doraemonkit.kit.core.UniversalActivity}: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class com.didichuxing.doraemonkit.widget.webview.MyWebView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
	at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class com.didichuxing.doraemonkit.widget.webview.MyWebView
Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class com.didichuxing.doraemonkit.widget.webview.MyWebView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.view.LayoutInflater.inflate(<Xposed>)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at com.didichuxing.doraemonkit.kit.core.BaseFragment.onCreateView(BaseFragment.java:50)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2950)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:515)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3122)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3056)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:473)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6740)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2629)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
	at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.UnsupportedOperationException: For security reasons, WebView is not allowed in privileged processes
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:187)
	at android.webkit.WebView.getFactory(WebView.java:2341)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2336)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2395)
	at android.view.View.<init>(View.java:4023)
	at android.view.View.<init>(View.java:4146)
	at android.view.ViewGroup.<init>(ViewGroup.java:579)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
	at android.webkit.WebView.<init>(WebView.java:627)
	at android.webkit.WebView.<init>(WebView.java:572)
	at android.webkit.WebView.<init>(WebView.java:555)
	at android.webkit.WebView.<init>(WebView.java:542)
	at com.didichuxing.doraemonkit.widget.webview.MyWebView.<init>(MyWebView.java:40)

**Comment by jtsky** [comment]
> java stacktrace:
> java.lang.RuntimeException: Unable to start activity ComponentInfo{/com.didichuxing.doraemonkit.kit.core.UniversalActivity}: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class com.didichuxing.doraemonkit.widget.webview.MyWebView
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
> at android.app.ActivityThread.-wrap12(ActivityThread.java)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
> at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:44)
> at android.os.Handler.dispatchMessage(Handler.java:98)
> at android.os.Looper.loop(Looper.java:154)
> at android.app.ActivityThread.main(ActivityThread.java:6121)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
> at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
> Caused by: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class com.didichuxing.doraemonkit.widget.webview.MyWebView
> Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class com.didichuxing.doraemonkit.widget.webview.MyWebView
> Caused by: java.lang.reflect.InvocationTargetException
> at java.lang.reflect.Constructor.newInstance0(Native Method)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
> at android.view.LayoutInflater.createView(LayoutInflater.java:645)
> at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
> at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
> at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
> at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
> at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
> at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
> at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
> at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
> at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
> at android.view.LayoutInflater.inflate()
> at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
> at com.didichuxing.doraemonkit.kit.core.BaseFragment.onCreateView(BaseFragment.java:50)
> at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2950)
> at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:515)
> at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
> at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
> at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
> at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
> at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3122)
> at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3056)
> at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
> at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:473)
> at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
> at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
> at android.app.Activity.performStart(Activity.java:6740)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2629)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
> at android.app.ActivityThread.-wrap12(ActivityThread.java)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
> at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:44)
> at android.os.Handler.dispatchMessage(Handler.java:98)
> at android.os.Looper.loop(Looper.java:154)
> at android.app.ActivityThread.main(ActivityThread.java:6121)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
> at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
> Caused by: java.lang.UnsupportedOperationException: For security reasons, WebView is not allowed in privileged processes
> at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:187)
> at android.webkit.WebView.getFactory(WebView.java:2341)
> at android.webkit.WebView.ensureProviderCreated(WebView.java:2336)
> at android.webkit.WebView.setOverScrollMode(WebView.java:2395)
> at android.view.View.(View.java:4023)
> at android.view.View.(View.java:4146)
> at android.view.ViewGroup.(ViewGroup.java:579)
> at android.widget.AbsoluteLayout.(AbsoluteLayout.java:55)
> at android.webkit.WebView.(WebView.java:627)
> at android.webkit.WebView.(WebView.java:572)
> at android.webkit.WebView.(WebView.java:555)
> at android.webkit.WebView.(WebView.java:542)
> at com.didichuxing.doraemonkit.widget.webview.MyWebView.(MyWebView.java:40)

你是不是在另外的进程中去使用了？
