### ISSUE TITLE
【DoKit生态场景】-描述出现的问题

### ISSUE THREAD

**Issue by lixiaonan03** [didi/DoraemonKit#824]
android 小米8 使用 flutter ^0.8.0-nullsafety.0   这个版本进入应用报错  flutter版本 2.0.4

报错信息如下：

Dart Unhandled Exception: Bad state: implemented internally, stack trace: #0      Nested.build (package:nested/nested.dart:81:5)
E/flutter ( 9977): #1      _DoKitWrapper.build (package:dokit/ui/dokit_app.dart:52:52)
E/flutter ( 9977): #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4569:28)
E/flutter ( 9977): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
E/flutter ( 9977): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
E/flutter ( 9977): #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2694:33)
E/flutter ( 9977): #6      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:873:21)
E/flutter ( 9977): #7      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5

oSuchMethodError: The getter 'headers' was called on null.
Receiver: null
Tried calling: headers
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      DoKitHttpClientRequest.headers (package:dokit/engine/dokit_http.dart:237:37)
#2      _WebSocketImpl.connect.<anonymous closure> (dart:_http/websocket_impl.dart:1036:15)
#3      _rootRunUnary (dart:async/zone.dart:1362:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:539:5)
#9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:254:13)
#10     DoKitHttpClient.monitor (package:dokit/engine/dokit_http.dart)
<asynchronous suspension>

**Comment by hhstore** [comment]
+1

- `^0.8.0-nullsafety.0` 这个版本, 应该有些 bug 还没修. 没法用.

**Comment by zhugeafanti** [comment]
https://pub.dev/packages/dokit/versions/0.8.1-nullsafety.0
