### ISSUE TITLE
【Android】启动会崩溃

### ISSUE THREAD

**Issue by ChenJunXu** [didi/DoraemonKit#850]
版本：3.4.0-alpha02
机型：一加6T（跟机型应该没关系）

2021-06-22 17:49:35.496 27370-27459/com.xu.xu E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.xu.xu, PID: 27370
    java.lang.ExceptionInInitializerError
        at com.didichuxing.doraemonkit.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:104)
        at com.didichuxing.doraemonkit.util.Utils.getApp(Utils.java:71)
        at com.didichuxing.doraemonkit.util.DoKitSPUtil.getSharedPrefs(DoKitSPUtil.java:30)
        at com.didichuxing.doraemonkit.util.DoKitSPUtil.getSharedPrefs(DoKitSPUtil.java:25)
        at com.didichuxing.doraemonkit.util.DoKitSPUtil.getBoolean(DoKitSPUtil.java:76)
        at com.didichuxing.doraemonkit.config.GlobalConfig.getAppHealth(GlobalConfig.java:29)
        at com.didichuxing.doraemonkit.constant.DoKitConstant.<clinit>(DoKitConstant.kt:80)
        at com.didichuxing.doraemonkit.constant.DoKitConstant.dealDidiPlatformPath(Unknown Source:0)
        at com.didichuxing.doraemonkit.kit.network.room_db.DokitDbManager.mockMatched(DokitDbManager.java:393)
        at com.didichuxing.doraemonkit.kit.network.room_db.DokitDbManager.isMockMatched(DokitDbManager.java:370)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:69)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitCapInterceptor.intercept(DokitCapInterceptor.java:46)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitLargePicInterceptor.intercept(DokitLargePicInterceptor.java:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:49)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitCapInterceptor.intercept(DokitCapInterceptor.java:46)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitLargePicInterceptor.intercept(DokitLargePicInterceptor.java:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:49)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitCapInterceptor.intercept(DokitCapInterceptor.java:46)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitLargePicInterceptor.intercept(DokitLargePicInterceptor.java:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:49)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2021-06-22 17:49:35.499 27370-27459/com.xu.xu E/AndroidRuntime:     at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitCapInterceptor.intercept(DokitCapInterceptor.java:46)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitLargePicInterceptor.intercept(DokitLargePicInterceptor.java:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:49)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.RuntimeException: Can't create handler inside thread Thread[OkHttp http://api.fc.mob.com/...,5,main] that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:207)
        at android.os.Handler.<init>(Handler.java:119)
        at android.app.Activity.<init>(Activity.java:880)
        at com.didichuxing.doraemonkit.util.UtilsActivityLifecycleImpl.<clinit>(UtilsActivityLifecycleImpl.java:42)
        	... 55 more

**Comment by jtsky** [comment]
> 版本：3.4.0-alpha02
> 机型：一加6T（跟机型应该没关系）
> 
> 2021-06-22 17:49:35.496 27370-27459/com.xu.xu E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
> Process: com.xu.xu, PID: 27370
> java.lang.ExceptionInInitializerError
> at com.didichuxing.doraemonkit.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:104)
> at com.didichuxing.doraemonkit.util.Utils.getApp(Utils.java:71)
> at com.didichuxing.doraemonkit.util.DoKitSPUtil.getSharedPrefs(DoKitSPUtil.java:30)
> at com.didichuxing.doraemonkit.util.DoKitSPUtil.getSharedPrefs(DoKitSPUtil.java:25)
> at com.didichuxing.doraemonkit.util.DoKitSPUtil.getBoolean(DoKitSPUtil.java:76)
> at com.didichuxing.doraemonkit.config.GlobalConfig.getAppHealth(GlobalConfig.java:29)
> at com.didichuxing.doraemonkit.constant.DoKitConstant.(DoKitConstant.kt:80)
> at com.didichuxing.doraemonkit.constant.DoKitConstant.dealDidiPlatformPath(Unknown Source:0)
> at com.didichuxing.doraemonkit.kit.network.room_db.DokitDbManager.mockMatched(DokitDbManager.java:393)
> at com.didichuxing.doraemonkit.kit.network.room_db.DokitDbManager.isMockMatched(DokitDbManager.java:370)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:69)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitCapInterceptor.intercept(DokitCapInterceptor.java:46)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitLargePicInterceptor.intercept(DokitLargePicInterceptor.java:32)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:49)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitCapInterceptor.intercept(DokitCapInterceptor.java:46)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitLargePicInterceptor.intercept(DokitLargePicInterceptor.java:32)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:49)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitCapInterceptor.intercept(DokitCapInterceptor.java:46)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitLargePicInterceptor.intercept(DokitLargePicInterceptor.java:32)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:49)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> 2021-06-22 17:49:35.499 27370-27459/com.xu.xu E/AndroidRuntime: at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitCapInterceptor.intercept(DokitCapInterceptor.java:46)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitLargePicInterceptor.intercept(DokitLargePicInterceptor.java:32)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:49)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
> at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
> at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:919)
> Caused by: java.lang.RuntimeException: Can't create handler inside thread Thread[OkHttp http://api.fc.mob.com/...,5,main] that has not called Looper.prepare()
> at android.os.Handler.(Handler.java:207)
> at android.os.Handler.(Handler.java:119)
> at android.app.Activity.(Activity.java:880)
> at com.didichuxing.doraemonkit.util.UtilsActivityLifecycleImpl.(UtilsActivityLifecycleImpl.java:42)
> ... 55 more

试试3.4.0-alpha04版本

**Comment by ChenJunXu** [comment]
@jtsky 3.4.0-alpha04 版本也会。最开始使用 3.4.0-alpha04 版本，发现崩溃后改成 3.4.0-alpha02，仍然启动时会崩溃

**Comment by chen3441251** [comment]
一样的问题：
版本：3.4.0-alpha04
机型：MI9 pro

Build version: 1.4.0 
Build date: 1981-01-01 01:01:02 
Current date: 2021-06-28 18:16:25 
Device: Xiaomi Mi9 Pro 5G 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.ExceptionInInitializerError
at com.didichuxing.doraemonkit.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:104)
at com.didichuxing.doraemonkit.util.Utils.getApp(Utils.java:71)
at com.didichuxing.doraemonkit.util.DoKitSPUtil.getSharedPrefs(DoKitSPUtil.java:30)
at com.didichuxing.doraemonkit.util.DoKitSPUtil.getSharedPrefs(DoKitSPUtil.java:25)
at com.didichuxing.doraemonkit.util.DoKitSPUtil.getBoolean(DoKitSPUtil.java:76)
at com.didichuxing.doraemonkit.config.GlobalConfig.getAppHealth(GlobalConfig.java:29)
at com.didichuxing.doraemonkit.constant.DoKitConstant.<clinit>(DoKitConstant.kt:81)
at com.didichuxing.doraemonkit.constant.DoKitConstant.dealDidiPlatformPath(Unknown Source:0)
at com.didichuxing.doraemonkit.kit.network.room_db.DokitDbManager.mockMatched(DokitDbManager.java:393)
at com.didichuxing.doraemonkit.kit.network.room_db.DokitDbManager.isMockMatched(DokitDbManager.java:370)
at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:69)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitExtInterceptor.intercept(DokitExtInterceptor.kt:16)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitCapInterceptor.intercept(DokitCapInterceptor.java:46)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitLargePicInterceptor.intercept(DokitLargePicInterceptor.java:32)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:49)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitExtInterceptor.intercept(DokitExtInterceptor.kt:16)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitCapInterceptor.intercept(DokitCapInterceptor.java:46)
at okhttp3. internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitLargePicInterceptor.intercept(DokitLargePicInterceptor.java:32)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:49)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitExtInterceptor.intercept(DokitExtInterceptor.kt:16)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitCapInterceptor.intercept(DokitCapInterceptor.java:46)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitLargePicInterceptor.intercept(DokitLargePicInterceptor.java:32)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:49)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
at okhttp3.RealCall.execute(RealCall.java:81)
at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$OkHttpURLConnection.getResponse(ObsoleteUrlFactory.java:653)
at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$OkHttpURLConnection.getInputStream(ObsoleteUrlFactory.java:460)
at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$DelegatingHttpsURLConnection.getInputStream(ObsoleteUrlFactory.java:1167)
at com.megvii.licensemanager.Manager.doPost(Manager.java:129)
at com.megvii.licensemanager.Manager.takeLicenseFromNetwork(Manager.java:106)
at com.vcredit.yxtree.helper.InitSdkHelper$initFacePlus$1.run(InitSdkHelper.kt:218)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.RuntimeException: Can't create handler inside thread Thread[Thread-2,5,main] that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:207)
at android.os.Handler.<init>(Handler.java:119)
at android.app.Activity.<init>(Activity.java:897)
at com.didichuxing.doraemonkit.util.UtilsActivityLifecycleImpl.<clinit>(UtilsActivityLifecycleImpl.java:42)
... 58 more

**Comment by jtsky** [comment]
> 一样的问题：
> 版本：3.4.0-alpha04
> 机型：MI9 pro
> 
> Build version: 1.4.0
> Build date: 1981-01-01 01:01:02
> Current date: 2021-06-28 18:16:25
> Device: Xiaomi Mi9 Pro 5G
> OS version: Android 10 (SDK 29)
> 
> Stack trace:
> java.lang.ExceptionInInitializerError
> at com.didichuxing.doraemonkit.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:104)
> at com.didichuxing.doraemonkit.util.Utils.getApp(Utils.java:71)
> at com.didichuxing.doraemonkit.util.DoKitSPUtil.getSharedPrefs(DoKitSPUtil.java:30)
> at com.didichuxing.doraemonkit.util.DoKitSPUtil.getSharedPrefs(DoKitSPUtil.java:25)
> at com.didichuxing.doraemonkit.util.DoKitSPUtil.getBoolean(DoKitSPUtil.java:76)
> at com.didichuxing.doraemonkit.config.GlobalConfig.getAppHealth(GlobalConfig.java:29)
> at com.didichuxing.doraemonkit.constant.DoKitConstant.(DoKitConstant.kt:81)
> at com.didichuxing.doraemonkit.constant.DoKitConstant.dealDidiPlatformPath(Unknown Source:0)
> at com.didichuxing.doraemonkit.kit.network.room_db.DokitDbManager.mockMatched(DokitDbManager.java:393)
> at com.didichuxing.doraemonkit.kit.network.room_db.DokitDbManager.isMockMatched(DokitDbManager.java:370)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:69)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitExtInterceptor.intercept(DokitExtInterceptor.kt:16)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitCapInterceptor.intercept(DokitCapInterceptor.java:46)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitLargePicInterceptor.intercept(DokitLargePicInterceptor.java:32)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:49)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitExtInterceptor.intercept(DokitExtInterceptor.kt:16)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitCapInterceptor.intercept(DokitCapInterceptor.java:46)
> at okhttp3. internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitLargePicInterceptor.intercept(DokitLargePicInterceptor.java:32)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:49)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitExtInterceptor.intercept(DokitExtInterceptor.kt:16)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitCapInterceptor.intercept(DokitCapInterceptor.java:46)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitLargePicInterceptor.intercept(DokitLargePicInterceptor.java:32)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DokitMockInterceptor.intercept(DokitMockInterceptor.java:49)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
> at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
> at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
> at okhttp3.RealCall.execute(RealCall.java:81)
> at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$OkHttpURLConnection.getResponse(ObsoleteUrlFactory.java:653)
> at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$OkHttpURLConnection.getInputStream(ObsoleteUrlFactory.java:460)
> at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$DelegatingHttpsURLConnection.getInputStream(ObsoleteUrlFactory.java:1167)
> at com.megvii.licensemanager.Manager.doPost(Manager.java:129)
> at com.megvii.licensemanager.Manager.takeLicenseFromNetwork(Manager.java:106)
> at com.vcredit.yxtree.helper.InitSdkHelper$initFacePlus$1.run(InitSdkHelper.kt:218)
> at java.lang.Thread.run(Thread.java:919)
> Caused by: java.lang.RuntimeException: Can't create handler inside thread Thread[Thread-2,5,main] that has not called Looper.prepare()
> at android.os.Handler.(Handler.java:207)
> at android.os.Handler.(Handler.java:119)
> at android.app.Activity.(Activity.java:897)
> at com.didichuxing.doraemonkit.util.UtilsActivityLifecycleImpl.(UtilsActivityLifecycleImpl.java:42)
> ... 58 more

我大概知道是什么问题导致的了，你把dokit的初始化放到 Application onCreate()的最上面(优先初始化)

**Comment by Mubly** [comment]
我也遇到这问题，情况一样
