### ISSUE TITLE
NoClassDefFoundError UtilsActivityLifecycleImpl

### ISSUE THREAD

**Issue by mikaelzero** [didi/DoraemonKit#863]
> Android 还是 iOS？系统版本是多少？手机品牌是什么？Android Mi9
> 问题重现的步骤。启动崩溃

 java.lang.NoClassDefFoundError: com.didichuxing.doraemonkit.util.UtilsActivityLifecycleImpl
        at com.didichuxing.doraemonkit.util.UtilsBridge.addOnAppStatusChangedListener(UtilsBridge.java:70)
        at com.didichuxing.doraemonkit.util.AppUtils.registerAppStatusChangedListener(AppUtils.java:44)
        at com.didichuxing.doraemonkit.DoKitReal.registerModuleListener(DoKitReal.kt:170)
        at com.didichuxing.doraemonkit.DoKitReal.install(DoKitReal.kt:61)
        at com.didichuxing.doraemonkit.DoKit$Builder.build(DoKit.kt:308)
        at xxx.xxx.xxx.App.onCreate(App.kt:31)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6580)
        at android.app.ActivityThread.access$1400(ActivityThread.java:224)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

3.4.2版本
gradle 版本 6.8.4
agp版本4.2.2

**Comment by jtsky** [comment]
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？Android Mi9
> > 问题重现的步骤。启动崩溃
> 
> java.lang.NoClassDefFoundError: com.didichuxing.doraemonkit.util.UtilsActivityLifecycleImpl
> at com.didichuxing.doraemonkit.util.UtilsBridge.addOnAppStatusChangedListener(UtilsBridge.java:70)
> at com.didichuxing.doraemonkit.util.AppUtils.registerAppStatusChangedListener(AppUtils.java:44)
> at com.didichuxing.doraemonkit.DoKitReal.registerModuleListener(DoKitReal.kt:170)
> at com.didichuxing.doraemonkit.DoKitReal.install(DoKitReal.kt:61)
> at com.didichuxing.doraemonkit.DoKit$Builder.build(DoKit.kt:308)
> at xxx.xxx.xxx.App.onCreate(App.kt:31)
> at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
> at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6580)
> at android.app.ActivityThread.access$1400(ActivityThread.java:224)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
> at android.os.Handler.dispatchMessage(Handler.java:107)
> at android.os.Looper.loop(Looper.java:224)
> at android.app.ActivityThread.main(ActivityThread.java:7560)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
> 
> 3.4.2版本
> gradle 版本 6.8.4
> agp版本4.2.2

这种问题一般都是编译导致的  请检查是否其他的三方插件 导致了编译没有完全

**Comment by jtsky** [comment]
或者是系统版本太低也有可能

**Comment by jtsky** [comment]
> > > Android 还是 iOS？系统版本是多少？手机品牌是什么？Android Mi9
> > > 问题重现的步骤。启动崩溃
> > 
> > 
> > java.lang.NoClassDefFoundError: com.didichuxing.doraemonkit.util.UtilsActivityLifecycleImpl
> > at com.didichuxing.doraemonkit.util.UtilsBridge.addOnAppStatusChangedListener(UtilsBridge.java:70)
> > at com.didichuxing.doraemonkit.util.AppUtils.registerAppStatusChangedListener(AppUtils.java:44)
> > at com.didichuxing.doraemonkit.DoKitReal.registerModuleListener(DoKitReal.kt:170)
> > at com.didichuxing.doraemonkit.DoKitReal.install(DoKitReal.kt:61)
> > at com.didichuxing.doraemonkit.DoKit$Builder.build(DoKit.kt:308)
> > at xxx.xxx.xxx.App.onCreate(App.kt:31)
> > at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
> > at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6580)
> > at android.app.ActivityThread.access$1400(ActivityThread.java:224)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
> > at android.os.Handler.dispatchMessage(Handler.java:107)
> > at android.os.Looper.loop(Looper.java:224)
> > at android.app.ActivityThread.main(ActivityThread.java:7560)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
> > 3.4.2版本
> > gradle 版本 6.8.4
> > agp版本4.2.2
> 
> 这种问题一般都是编译导致的 请检查是否其他的三方插件 导致了编译没有完全

参考：https://help.aliyun.com/document_detail/56936.html

**Comment by mikaelzero** [comment]
测了几款机型  只有小米9会出现这个问题

**Comment by jtsky** [comment]
> 测了几款机型 只有小米9会出现这个问题

不是小米全系？是只有小米9是吗？能确定下miui版本吗？

**Comment by mikaelzero** [comment]
手上只有小米9
版本是12.0.6
