### ISSUE TITLE
【Flutter】-dokit拦截网络请求时输出异常

### ISSUE THREAD

**Issue by siyukok** [didi/DoraemonKit#869]
请补充如下信息。
> Android 还是 iOS？系统版本是多少？手机品牌是什么？
iOS平台
手机型号：iPhone8 plus
系统版本：13.5.1
网络请求框架：Dio 3.0.9
> 期望的表现和实际的表现。
成功拦截所有网络请求，目前只有少部分请求能够捕获到并显示到网络请求列表中
> 问题重现的步骤。（如有）
进行网络请求
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
日志如下
FormatException: Unfinished UTF-8 octet sequence (at offset 394)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1783:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:321:42)
#2      Utf8Codec.decode (dart:convert/utf.dart:62:20)
#3      DoKitHttpClientResponse.transform.<anonymous closure> (package:dokit/engine/dokit_http.dart:618:52)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#9      _SyncBroadcastStreamController._sendData.<anonymous closure> (dart:async/broadcast_stream_controller.dart:393:20)
#10     _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:330:15)
#11     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:392:5)
#12     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#13     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:484:11)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#19     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#20     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#21     DefaultHttpClientAdapter.fetch.<anonymous closure> (package:dio/src/adapters/io_adapter.dart:77:14)
#22     _HandlerEventSink.add (dart:async/stream_transformers.dart:225:17)
#23     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#24     _rootRunUnary (dart:async/zone.dart:1198:47)
#25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#29     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
#30     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:266:10)
#31     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
#32     _rootRunUnary (dart:async/zone.dart:1198:47)
#33     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#37     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#38     _StreamController._add (dart:async/stream_controller.dart:682:7)
#39     _StreamController.add (dart:async/stream_controller.dart:624:5)
#40     _HttpParser._doParse (dart:_http/http_parser.dart:809:28)
#41     _HttpParser._parse (dart:_http/http_parser.dart:324:7)
#42     _HttpParser._onData (dart:_http/http_parser.dart:853:5)
#43     _rootRunUnary (dart:async/zone.dart:1198:47)
#44     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#48     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#49     _StreamController._add (dart:async/stream_controller.dart:682:7)
#50     _StreamController.add (dart:async/stream_controller.dart:624:5)
#51     _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
#52     _rootRunUnary (dart:async/zone.dart:1206:13)
#53     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#57     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#58     _StreamController._add (dart:async/stream_controller.dart:682:7)
#59     _StreamController.add (dart:async/stream_controller.dart:624:5)
#60     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#61     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
#62     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by yulongfy** [comment]
我也遇到了这个问题，可以在Utf8Codec.decode的时候try-catch一下
