### ISSUE TITLE
一机多控崩溃 NoClassDefFoundError: Failed resolution of: Lio/ktor/client/engine/cio/CIO;

### ISSUE THREAD

**Issue by ljz2009y** [didi/DoraemonKit#871]
请补充如下信息。
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
Android系统版本 Android11 ，:Xiaomi Mi 10 Pro 

gradle版本 gradle-5.4.1-all.zip
kotlin_version           = "1.4.20",
kotlinx_coroutines_core  = "1.4.2",

dokit 版本
    debugImplementation "io.github.didi.dokit:dokitx:3.4.2.1"
    debugImplementation "io.github.didi.dokit:dokitx-mc:3.4.2.1"

> 期望的表现和实际的表现。（如有）
运行一机多控，主机生成二维码之后，使用从机扫码之后crash
Stack trace:  
java.lang.NoClassDefFoundError: Failed resolution of: Lio/ktor/client/engine/cio/CIO;
 at com.didichuxing.doraemonkit.kit.mc.client.DoKitWsClient$client$2.invoke(DoKitWsClient.kt:51)
 at com.didichuxing.doraemonkit.kit.mc.client.DoKitWsClient$client$2.invoke(DoKitWsClient.kt:31)
 at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
 at com.didichuxing.doraemonkit.kit.mc.client.DoKitWsClient.getClient(Unknown Source:2)
 at com.didichuxing.doraemonkit.kit.mc.client.DoKitWsClient.access$getClient$p(DoKitWsClient.kt:31)
 at com.didichuxing.doraemonkit.kit.mc.client.DoKitWsClient$connect$1.invokeSuspend(DoKitWsClient.kt:60)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.ClassNotFoundException: Didn't find class "io.ktor.client.engine.cio.CIO" on path: DexPathList[[zip file "/data/app/~~RuhdOUdtlcG3i56nbrZmsw==/com.fiture.taurus-mVEDUzEDGC_N8Te-9CtLjQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~RuhdOUdtlcG3i56nbrZmsw==/com.fiture.taurus-mVEDUzEDGC_N8Te-9CtLjQ==/lib/arm64, /data/app/~~RuhdOUdtlcG3i56nbrZmsw==/com.fiture.taurus-mVEDUzEDGC_N8Te-9CtLjQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 ... 12 more

> 问题重现的步骤。（如有）

**Comment by jtsky** [comment]
> 请补充如下信息。
> 
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> > Android系统版本 Android11 ，:Xiaomi Mi 10 Pro
> 
> gradle版本 gradle-5.4.1-all.zip
> kotlin_version = "1.4.20",
> kotlinx_coroutines_core = "1.4.2",
> 
> dokit 版本
> debugImplementation "io.github.didi.dokit:dokitx:3.4.2.1"
> debugImplementation "io.github.didi.dokit:dokitx-mc:3.4.2.1"
> 
> > 期望的表现和实际的表现。（如有）
> > 运行一机多控，主机生成二维码之后，使用从机扫码之后crash
> > Stack trace:
> > java.lang.NoClassDefFoundError: Failed resolution of: Lio/ktor/client/engine/cio/CIO;
> > at com.didichuxing.doraemonkit.kit.mc.client.DoKitWsClient$client$2.invoke(DoKitWsClient.kt:51)
> > at com.didichuxing.doraemonkit.kit.mc.client.DoKitWsClient$client$2.invoke(DoKitWsClient.kt:31)
> > at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
> > at com.didichuxing.doraemonkit.kit.mc.client.DoKitWsClient.getClient(Unknown Source:2)
> > at com.didichuxing.doraemonkit.kit.mc.client.DoKitWsClient.access$getClient$p(DoKitWsClient.kt:31)
> > at com.didichuxing.doraemonkit.kit.mc.client.DoKitWsClient$connect$1.invokeSuspend(DoKitWsClient.kt:60)
> > at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> > at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> > at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> > at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
> > at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> > at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> > Caused by: java.lang.ClassNotFoundException: Didn't find class "io.ktor.client.engine.cio.CIO" on path: DexPathList[[zip file "/data/app/~~RuhdOUdtlcG3i56nbrZmsw==/com.fiture.taurus-mVEDUzEDGC_N8Te-9CtLjQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~RuhdOUdtlcG3i56nbrZmsw==/com.fiture.taurus-mVEDUzEDGC_N8Te-9CtLjQ==/lib/arm64, /data/app/~~RuhdOUdtlcG3i56nbrZmsw==/com.fiture.taurus-mVEDUzEDGC_N8Te-9CtLjQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
> > at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
> > at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> > at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> > ... 12 more
> 
> > 问题重现的步骤。（如有）

建议升级到最新的dokit版本试试 然后还是出现这个错误的话 可以试试在dokit的相关依赖下单独引入io.ktor:ktor-client-okhttp:1.5.4 用来替换成cio
