### ISSUE TITLE
ViewCheckInfoFloatPage Crash 

### ISSUE THREAD

**Issue by GJson** [didi/DoraemonKit#91]
Please complete the following informations.
> 控件检查功能不可用.
> 控件检查---选取view后crash
> Android  doraemonkit:1.1.1
>error log 
java.lang.ClassCastException: activity.CourseDetailActivity cannot be cast to android.support.v7.app.AppCompatActivity
        at com.didichuxing.doraemonkit.kit.viewcheck.ViewCheckInfoFloatPage.onViewSelected(ViewCheckInfoFloatPage.java:131)
        at com.didichuxing.doraemonkit.kit.viewcheck.ViewCheckFloatPage.onViewSelected(ViewCheckFloatPage.java:160)
        at com.didichuxing.doraemonkit.kit.viewcheck.ViewCheckFloatPage.onUp(ViewCheckFloatPage.java:150)
        at com.didichuxing.doraemonkit.ui.base.TouchProxy.onTouchEvent(TouchProxy.java:65)
        at com.didichuxing.doraemonkit.kit.viewcheck.ViewCheckFloatPage$2.onTouch(ViewCheckFloatPage.java:83)
        at android.view.View.dispatchTouchEvent(View.java:9308)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2550)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
        at android.view.View.dispatchPointerEvent(View.java:9536)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4281)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4144)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3683)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3736)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3702)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3828)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3710)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3885)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3683)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3736)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3702)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3710)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3683)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5973)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5947)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5908)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6079)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:195)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:141)
        at android.app.ActivityThread.main(ActivityThread.java:5653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by LinJZong** [comment]
新版本修复，感谢反馈
