### ISSUE TITLE
【Android】-启动崩溃（离线推送消息处理页面逻辑下，具体见描述）

### ISSUE THREAD

**Issue by Felix8029** [didi/DoraemonKit#948]
1、App未打开
2、接收到离线推送，点击推送，会打开一个消息处理页面，处理完即finish，并且唤起App主页
在唤起过程中如下错误：

AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fanggeek.agent, PID: 15455
    java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter activity
        at com.didichuxing.doraemonkit.DoKit$Companion.getDoKitView(Unknown Source:2)
        at com.didichuxing.doraemonkit.DoKit.getDoKitView(Unknown Source:2)
        at com.didichuxing.doraemonkit.kit.timecounter.counter.ActivityCounter.print(ActivityCounter.java:145)
        at com.didichuxing.doraemonkit.kit.timecounter.counter.ActivityCounter.renderEnd(ActivityCounter.java:115)
        at com.didichuxing.doraemonkit.kit.timecounter.counter.ActivityCounter.render(ActivityCounter.java:98)
        at com.didichuxing.doraemonkit.kit.timecounter.counter.ActivityCounter.launchEnd(ActivityCounter.java:78)
        at com.didichuxing.doraemonkit.kit.timecounter.TimeCounterManager.onActivityLaunched(TimeCounterManager.java:109)
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.postDispatch(ProxyHandlerCallback.java:86)
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:45)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by alvince** [comment]
用的哪个版本，模拟了一下没复现 @Felix8029

**Comment by Felix8029** [comment]
> 用的哪个版本，模拟了一下没复现 @Felix8029

3.4.2

**Comment by alvince** [comment]
> > 用的哪个版本，模拟了一下没复现 @Felix8029
> 
> 3.4.2

https://github.com/didi/DoraemonKit/blob/master/Doc/android-ReleaseNotes.md
参考这里先升级一下版本试试 @Felix8029
