### ISSUE TITLE
【Android】【3.5.0.1】-实时导航功能发生异常不可用

### ISSUE THREAD

**Issue by BryceCui** [didi/DoraemonKit#951]
高德地图导航版本：
amapNavi3dmap = 'com.amap.api:navi-3dmap:8.1.0_3dmap8.1.0',
DoKit版本："io.github.didi.dokit:dokitx:3.5.0.1"
异常信息：
2021-11-23 14:06:53.805 E/navi: 隐私合规校验失败：
    errorCode : 555570
    原因：***确保调用SDK任何接口前先调用更新隐私合规updatePrivacyShow、updatePrivacyAgree两个接口并且参数值都为true，若未正确设置有崩溃风险***
    使用navi SDK 功能前请设置隐私权政策是否弹窗告知用户
2021-11-23 14:06:53.806 V/Doraemon:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ main, com.didichuxing.doraemonkit.util.LogHelper.e(LogHelper.java:29)
    │       com.didichuxing.doraemonkit.kit.core.AbsDokitView.performCreate(AbsDokitView.kt:259)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ [com.didichuxing.doraemonkit.kit.lbs.route.AMapRealNavMockView]: e===>***确保调用SDK任何接口前先调用更新隐私合规updatePrivacyShow、updatePrivacyAgree两个接口并且参数值都为true，若未正确设置有崩溃风险***
    │ 使用navi SDK 功能前请设置隐私权政策是否弹窗告知用户
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-11-23 14:06:53.806 W/System.err: com.amap.api.maps.AMapException: ***确保调用SDK任何接口前先调用更新隐私合规updatePrivacyShow、updatePrivacyAgree两个接口并且参数值都为true，若未正确设置有崩溃风险***
2021-11-23 14:06:53.806 W/System.err: 使用navi SDK 功能前请设置隐私权政策是否弹窗告知用户
2021-11-23 14:06:53.806 W/System.err:     at com.amap.api.navi.AMapNavi.getInstance(AMapNavi.java:72)
2021-11-23 14:06:53.806 W/System.err:     at com.didichuxing.doraemonkit.kit.lbs.route.AMapRealNavMockView.onCreate(AMapRealNavMockView.kt:43)
2021-11-23 14:06:53.806 W/System.err:     at com.didichuxing.doraemonkit.kit.core.AbsDokitView.performCreate(AbsDokitView.kt:174)
2021-11-23 14:06:53.807 W/System.err:     at com.didichuxing.doraemonkit.kit.core.SystemDoKitViewManager.attach(SystemDoKitViewManager.kt:235)
2021-11-23 14:06:53.807 W/System.err:     at com.didichuxing.doraemonkit.kit.core.DokitViewManager.attach(DokitViewManager.kt:160)
2021-11-23 14:06:53.807 W/System.err:     at com.didichuxing.doraemonkit.kit.core.SimpleDoKitLauncher.launchFloating(SimpleDoKitLauncher.kt:28)
2021-11-23 14:06:53.807 W/System.err:     at com.didichuxing.doraemonkit.DoKitReal.launchFloating(DoKitReal.kt:536)
2021-11-23 14:06:53.807 W/System.err:     at com.didichuxing.doraemonkit.DoKit$Companion.launchFloating(DoKit.kt:90)
2021-11-23 14:06:53.807 W/System.err:     at com.didichuxing.doraemonkit.DoKit$Companion.launchFloating(DoKit.kt:106)
2021-11-23 14:06:53.807 W/System.err:     at com.didichuxing.doraemonkit.DoKit$Companion.launchFloating$default(DoKit.kt:104)
2021-11-23 14:06:53.807 W/System.err:     at com.didichuxing.doraemonkit.kit.lbs.route.RealNavMockKit.onClickWithReturn(RealNavMockKit.kt:39)
2021-11-23 14:06:53.807 W/System.err:     at com.didichuxing.doraemonkit.kit.toolpanel.ToolPanelDoKitView$initView$3.onItemClick(ToolPanelDoKitView.kt:126)
2021-11-23 14:06:53.807 W/System.err:     at com.didichuxing.doraemonkit.widget.brvah.BaseQuickAdapter.setOnItemClick(BaseQuickAdapter.kt:575)
2021-11-23 14:06:53.807 W/System.err:     at com.didichuxing.doraemonkit.widget.brvah.BaseQuickAdapter$bindViewClickListener$$inlined$let$lambda$1.onClick(BaseQuickAdapter.kt:517)
2021-11-23 14:06:53.807 W/System.err:     at android.view.View.performClick(View.java:7498)
2021-11-23 14:06:53.807 W/System.err:     at android.view.View.performClickInternal(View.java:7475)
2021-11-23 14:06:53.807 W/System.err:     at android.view.View.access$3600(View.java:833)
2021-11-23 14:06:53.807 W/System.err:     at android.view.View$PerformClick.run(View.java:28663)
2021-11-23 14:06:53.807 W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2021-11-23 14:06:53.807 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-11-23 14:06:53.807 W/System.err:     at android.os.Looper.loop(Looper.java:236)
2021-11-23 14:06:53.807 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7876)
2021-11-23 14:06:53.807 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-11-23 14:06:53.807 W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
2021-11-23 14:06:53.807 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
2021-11-23 14:06:53.808 W/System.err: java.lang.IllegalArgumentException: view must not be null
2021-11-23 14:06:53.808 W/System.err:     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:334)
2021-11-23 14:06:53.808 W/System.err:     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:111)
2021-11-23 14:06:53.808 W/System.err:     at com.didichuxing.doraemonkit.kit.core.SystemDoKitViewManager.attach(SystemDoKitViewManager.kt:238)
2021-11-23 14:06:53.808 W/System.err:     at com.didichuxing.doraemonkit.kit.core.DokitViewManager.attach(DokitViewManager.kt:160)
2021-11-23 14:06:53.808 W/System.err:     at com.didichuxing.doraemonkit.kit.core.SimpleDoKitLauncher.launchFloating(SimpleDoKitLauncher.kt:28)
2021-11-23 14:06:53.808 W/System.err:     at com.didichuxing.doraemonkit.DoKitReal.launchFloating(DoKitReal.kt:536)
2021-11-23 14:06:53.808 W/System.err:     at com.didichuxing.doraemonkit.DoKit$Companion.launchFloating(DoKit.kt:90)
2021-11-23 14:06:53.808 W/System.err:     at com.didichuxing.doraemonkit.DoKit$Companion.launchFloating(DoKit.kt:106)
2021-11-23 14:06:53.808 W/System.err:     at com.didichuxing.doraemonkit.DoKit$Companion.launchFloating$default(DoKit.kt:104)
2021-11-23 14:06:53.808 W/System.err:     at com.didichuxing.doraemonkit.kit.lbs.route.RealNavMockKit.onClickWithReturn(RealNavMockKit.kt:39)
2021-11-23 14:06:53.808 W/System.err:     at com.didichuxing.doraemonkit.kit.toolpanel.ToolPanelDoKitView$initView$3.onItemClick(ToolPanelDoKitView.kt:126)
2021-11-23 14:06:53.808 W/System.err:     at com.didichuxing.doraemonkit.widget.brvah.BaseQuickAdapter.setOnItemClick(BaseQuickAdapter.kt:575)
2021-11-23 14:06:53.808 W/System.err:     at com.didichuxing.doraemonkit.widget.brvah.BaseQuickAdapter$bindViewClickListener$$inlined$let$lambda$1.onClick(BaseQuickAdapter.kt:517)
2021-11-23 14:06:53.808 W/System.err:     at android.view.View.performClick(View.java:7498)
2021-11-23 14:06:53.808 W/System.err:     at android.view.View.performClickInternal(View.java:7475)
2021-11-23 14:06:53.808 W/System.err:     at android.view.View.access$3600(View.java:833)
2021-11-23 14:06:53.808 W/System.err:     at android.view.View$PerformClick.run(View.java:28663)
2021-11-23 14:06:53.808 W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2021-11-23 14:06:53.808 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-11-23 14:06:53.808 W/System.err:     at android.os.Looper.loop(Looper.java:236)
2021-11-23 14:06:53.808 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7876)
2021-11-23 14:06:53.808 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-11-23 14:06:53.808 W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
2021-11-23 14:06:53.808 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by jaydroid1024** [comment]
关于高德地图隐私合规的适配已经在 [946](https://github.com/didi/DoraemonKit/pull/946) 中修复
