### ISSUE TITLE
type 'Null' is not a subtype of type 'FutureOr<_HttpClientRequest>'

### ISSUE THREAD

**Issue by robin2005** [didi/DoraemonKit#984]
Flutter 开发 断点调试异常

![1](https://user-images.githubusercontent.com/6906607/153528043-ec57c403-85b1-458c-a489-345b8386c0a7.png)

[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'FutureOr<_HttpClientRequest>'
#0      _FutureListener.handleError (dart:async/future_impl.dart:169:20)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:719:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:740:24)
#3      Future._completeError (dart:async/future_impl.dart:550:5)
#4      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:606:7)
#5      _rootRun (dart:async/zone.dart:1354:13)
#6      _CustomZone.run (dart:async/zone.dart:1258:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'FutureOr<_HttpClientRequest>'
#0      _FutureListener.handleError (dart:async/future_impl.dart:169:20)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:719:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:740:24)
#3      Future._completeError (dart:async/future_impl.dart:550:5)
#4      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:606:7)
#5      _rootRun (dart:async/zone.dart:1354:13)
#6      _CustomZone.run (dart:async/zone.dart:1258:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5) 
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
#0      VMServiceWrapper.callExtensionService (package:dokit/kit/apm/vm/vm_service_wrapper.dart:50:29)
#1      upLoadUserInfo (package:dokit/dokit.dart:263:8)
<asynchronous suspension>

**Comment by oopanda-sun** [comment]
请问解决了嘛

**Comment by robin2005** [comment]
> 请问解决了嘛

没有
