### ISSUE TITLE
【DoKit生态场景】每次进入页面 logcat 打印错误日志 java.lang.IllegalAccessException: Tried to access visual service WindowManager from a non-visual

### ISSUE THREAD

**Issue by twiceyuan** [didi/DoraemonKit#993]
> Android、iOS? OS version? Brand? 

Android

> Expected behavior and actual behavior.

没有错误日志输出

> Steps to reproduce the problem.

接入后，进入一个页面后即可

> More informations such as error messages and stack traces are welcomed.
>

建议提issues之前可以参考一下DoKit社区答疑流程：https://github.com/didi/DoraemonKit/issues/745
假如还是无法解决你的问题，你可以按照以下模板来提交你的issue

请补充如下信息。
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）

Android 11 - OnePlus 9R, Oxygen OS 11.2.8.8

> 期望的表现和实际的表现。

没有错误日志输出

> 问题重现的步骤。

接入后进入任意页面即可复现：

> 其他的错误信息和堆栈信息如果有也可以一并提供出来。
```
java.lang.IllegalAccessException: Tried to access visual service WindowManager from a non-visual Context:com.xxx.App@8d04d9
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1951)
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:803)
        at com.didichuxing.doraemonkit.kit.core.DokitViewManager.getWindowManager(DokitViewManager.kt:297)
        at com.didichuxing.doraemonkit.kit.core.AbsDokitView.<init>(AbsDokitView.kt:63)
        at com.didichuxing.doraemonkit.kit.main.MainIconDoKitView.<init>(MainIconDoKitView.kt:18)
        at java.lang.Class.newInstance(Native Method)
        at com.didichuxing.doraemonkit.kit.core.NormalDoKitViewManager.attach(NormalDoKitViewManager.kt:306)
        at com.didichuxing.doraemonkit.kit.core.NormalDoKitViewManager.attachMainIcon(NormalDoKitViewManager.kt:108)
        at com.didichuxing.doraemonkit.kit.core.NormalDoKitViewManager.onMainActivityResume(NormalDoKitViewManager.kt:139)
        at com.didichuxing.doraemonkit.kit.core.NormalDoKitViewManager.dispatchOnActivityResumed(NormalDoKitViewManager.kt:83)
        at com.didichuxing.doraemonkit.kit.core.DokitViewManager.dispatchOnActivityResumed(DokitViewManager.kt:138)
        at com.didichuxing.doraemonkit.DokitActivityLifecycleCallbacks.dispatchOnActivityResumed(DokitActivityLifecycleCallbacks.kt:178)
        at com.didichuxing.doraemonkit.DokitActivityLifecycleCallbacks.onActivityResumed(DokitActivityLifecycleCallbacks.kt:92)
        at android.app.Application.dispatchActivityResumed(Application.java:456)
        at android.app.Activity.dispatchActivityResumed(Activity.java:1379)
        at android.app.Activity.onResume(Activity.java:1911)
        at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:434)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1571)
        at android.app.Activity.performResume(Activity.java:8141)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4632)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4674)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2257)
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:44)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8030)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by twiceyuan** [comment]
确实是开了 StrictMode 才会有的，请忽略
